/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type {
  StripeBillingPortal,
  StripeCheckout,
  StripeCheckoutSession,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const createStripeBillingPortal = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<StripeBillingPortal>(
    { url: `/api/v1/stripe/billing-portal`, method: "POST", signal },
    options,
  );
};

export const getCreateStripeBillingPortalMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createStripeBillingPortal>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createStripeBillingPortal>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["createStripeBillingPortal"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createStripeBillingPortal>>,
    void
  > = () => {
    return createStripeBillingPortal(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateStripeBillingPortalMutationResult = NonNullable<
  Awaited<ReturnType<typeof createStripeBillingPortal>>
>;

export type CreateStripeBillingPortalMutationError = ErrorType<unknown>;

export const useCreateStripeBillingPortal = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createStripeBillingPortal>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createStripeBillingPortal>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getCreateStripeBillingPortalMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const createStripeCheckout = (
  stripeCheckout: StripeCheckout,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<StripeCheckoutSession>(
    {
      url: `/api/v1/stripe/checkout`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: stripeCheckout,
      signal,
    },
    options,
  );
};

export const getCreateStripeCheckoutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createStripeCheckout>>,
    TError,
    { data: StripeCheckout },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createStripeCheckout>>,
  TError,
  { data: StripeCheckout },
  TContext
> => {
  const mutationKey = ["createStripeCheckout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createStripeCheckout>>,
    { data: StripeCheckout }
  > = (props) => {
    const { data } = props ?? {};

    return createStripeCheckout(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateStripeCheckoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof createStripeCheckout>>
>;
export type CreateStripeCheckoutMutationBody = StripeCheckout;
export type CreateStripeCheckoutMutationError = ErrorType<unknown>;

export const useCreateStripeCheckout = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createStripeCheckout>>,
      TError,
      { data: StripeCheckout },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createStripeCheckout>>,
  TError,
  { data: StripeCheckout },
  TContext
> => {
  const mutationOptions = getCreateStripeCheckoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
