# Generated by Django 5.2 on 2026-01-23 18:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("addresses", "0001_initial"),
        ("numbering_systems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerTaxRate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255, null=True)),
                ("legal_number", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("currency", models.CharField(max_length=3, null=True)),
                ("net_payment_term", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="customers", to="accounts.account"
                    ),
                ),
                (
                    "billing_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_billing_address",
                        to="addresses.address",
                    ),
                ),
                (
                    "credit_note_numbering_system",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_note_numbering_customers",
                        to="numbering_systems.numberingsystem",
                    ),
                ),
                (
                    "invoice_numbering_system",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_numbering_customers",
                        to="numbering_systems.numberingsystem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
