# Generated by Django 5.2 on 2026-02-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        ("customers", "0001_initial"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="logo",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="customer_logo", to="files.file"
            ),
        ),
        migrations.AddField(
            model_name="shippingprofile",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_profile_address",
                to="addresses.address",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="default_shipping_profile",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="customers.shippingprofile"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_profiles",
            field=models.ManyToManyField(related_name="customers", to="customers.shippingprofile"),
        ),
        migrations.AlterUniqueTogether(
            name="billingprofiletaxrate",
            unique_together={("billing_profile", "tax_rate")},
        ),
    ]
