# Generated by Django 5.2 on 2026-02-06 00:00

from django.db import migrations, models


def set_customer_name(apps, _schema_editor):
    Customer = apps.get_model("customers", "Customer")
    for customer in Customer.objects.select_related("default_billing_profile"):
        billing_profile = customer.default_billing_profile
        customer.name = billing_profile.name if billing_profile else ""
        customer.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(set_customer_name, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name="billingprofile",
            name="name",
        ),
    ]
