# Generated by Django 5.2 on 2026-02-06 00:00

from django.db import migrations, models


def backfill_customer_tax_ids(apps, _schema_editor):
    Customer = apps.get_model("customers", "Customer")
    TaxId = apps.get_model("tax_ids", "TaxId")
    for customer in Customer.objects.all():
        tax_ids = TaxId.objects.filter(billing_profiles__customers=customer).distinct()
        if tax_ids:
            customer.tax_ids.add(*tax_ids)


class Migration(migrations.Migration):
    dependencies = [
        ("tax_ids", "0001_initial"),
        ("customers", "0003_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="tax_ids",
            field=models.ManyToManyField(related_name="customers", to="tax_ids.taxid"),
        ),
        migrations.RunPython(backfill_customer_tax_ids, migrations.RunPython.noop),
    ]
