# Generated by Django 5.2 on 2026-01-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_customer_shipping_and_address"),
        ("numbering_systems", "0001_initial"),
        ("tax_rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="credit_note_numbering_system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_note_numbering_customers",
                to="numbering_systems.numberingsystem",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="invoice_numbering_system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_numbering_customers",
                to="numbering_systems.numberingsystem",
            ),
        ),
        migrations.AlterField(
            model_name="customertaxrate",
            name="tax_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="customer_tax_rates", to="tax_rates.taxrate"
            ),
        ),
    ]
