# Generated by Django 5.2 on 2026-01-30 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_alter_customer_credit_note_numbering_system_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="language",
            field=models.CharField(choices=settings.LANGUAGES, max_length=10, null=True),
        ),
    ]
