# Generated by Django 5.2 on 2026-01-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0003_alter_price_currency_alter_pricetier_currency"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="is_used",
        ),
        migrations.AlterField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="prices", to="products.product"
            ),
        ),
    ]
