# Generated by Django 5.2 on 2026-01-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.CharField(max_length=2048),
        ),
    ]
