/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type {
  Invitation,
  InvitationAccept,
  InvitationCreate,
  InvitationsListParams,
  Member,
  PaginatedInvitationList,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const invitationsList = (
  params?: InvitationsListParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedInvitationList>(
    { url: `/api/v1/invitations`, method: "GET", params, signal },
    options,
  );
};

export const getInvitationsListQueryKey = (params?: InvitationsListParams) => {
  return [`/api/v1/invitations`, ...(params ? [params] : [])] as const;
};

export const getInvitationsListQueryOptions = <
  TData = Awaited<ReturnType<typeof invitationsList>>,
  TError = ErrorType<unknown>,
>(
  params?: InvitationsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invitationsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvitationsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invitationsList>>> = ({
    signal,
  }) => invitationsList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invitationsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvitationsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof invitationsList>>
>;
export type InvitationsListQueryError = ErrorType<unknown>;

export function useInvitationsList<
  TData = Awaited<ReturnType<typeof invitationsList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | InvitationsListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invitationsList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitationsList>>,
          TError,
          Awaited<ReturnType<typeof invitationsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInvitationsList<
  TData = Awaited<ReturnType<typeof invitationsList>>,
  TError = ErrorType<unknown>,
>(
  params?: InvitationsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invitationsList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitationsList>>,
          TError,
          Awaited<ReturnType<typeof invitationsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInvitationsList<
  TData = Awaited<ReturnType<typeof invitationsList>>,
  TError = ErrorType<unknown>,
>(
  params?: InvitationsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invitationsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useInvitationsList<
  TData = Awaited<ReturnType<typeof invitationsList>>,
  TError = ErrorType<unknown>,
>(
  params?: InvitationsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invitationsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getInvitationsListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getInvitationsListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof invitationsList>>,
  TError = ErrorType<unknown>,
>(
  params?: InvitationsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof invitationsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvitationsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invitationsList>>> = ({
    signal,
  }) => invitationsList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof invitationsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvitationsListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof invitationsList>>
>;
export type InvitationsListSuspenseQueryError = ErrorType<unknown>;

export function useInvitationsListSuspense<
  TData = Awaited<ReturnType<typeof invitationsList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | InvitationsListParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof invitationsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInvitationsListSuspense<
  TData = Awaited<ReturnType<typeof invitationsList>>,
  TError = ErrorType<unknown>,
>(
  params?: InvitationsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof invitationsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInvitationsListSuspense<
  TData = Awaited<ReturnType<typeof invitationsList>>,
  TError = ErrorType<unknown>,
>(
  params?: InvitationsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof invitationsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useInvitationsListSuspense<
  TData = Awaited<ReturnType<typeof invitationsList>>,
  TError = ErrorType<unknown>,
>(
  params?: InvitationsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof invitationsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getInvitationsListSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createInvitation = (
  invitationCreate: InvitationCreate,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Invitation>(
    {
      url: `/api/v1/invitations`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: invitationCreate,
      signal,
    },
    options,
  );
};

export const getCreateInvitationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createInvitation>>,
    TError,
    { data: InvitationCreate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createInvitation>>,
  TError,
  { data: InvitationCreate },
  TContext
> => {
  const mutationKey = ["createInvitation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createInvitation>>,
    { data: InvitationCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createInvitation(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createInvitation>>
>;
export type CreateInvitationMutationBody = InvitationCreate;
export type CreateInvitationMutationError = ErrorType<unknown>;

export const useCreateInvitation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createInvitation>>,
      TError,
      { data: InvitationCreate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createInvitation>>,
  TError,
  { data: InvitationCreate },
  TContext
> => {
  const mutationOptions = getCreateInvitationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const invitationsRetrieve = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Invitation>(
    { url: `/api/v1/invitations/${id}`, method: "GET", signal },
    options,
  );
};

export const getInvitationsRetrieveQueryKey = (id?: string) => {
  return [`/api/v1/invitations/${id}`] as const;
};

export const getInvitationsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof invitationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invitationsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvitationsRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof invitationsRetrieve>>
  > = ({ signal }) => invitationsRetrieve(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof invitationsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvitationsRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof invitationsRetrieve>>
>;
export type InvitationsRetrieveQueryError = ErrorType<unknown>;

export function useInvitationsRetrieve<
  TData = Awaited<ReturnType<typeof invitationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invitationsRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitationsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof invitationsRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInvitationsRetrieve<
  TData = Awaited<ReturnType<typeof invitationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invitationsRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitationsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof invitationsRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInvitationsRetrieve<
  TData = Awaited<ReturnType<typeof invitationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invitationsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useInvitationsRetrieve<
  TData = Awaited<ReturnType<typeof invitationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invitationsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getInvitationsRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getInvitationsRetrieveSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof invitationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof invitationsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvitationsRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof invitationsRetrieve>>
  > = ({ signal }) => invitationsRetrieve(id, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof invitationsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvitationsRetrieveSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof invitationsRetrieve>>
>;
export type InvitationsRetrieveSuspenseQueryError = ErrorType<unknown>;

export function useInvitationsRetrieveSuspense<
  TData = Awaited<ReturnType<typeof invitationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof invitationsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInvitationsRetrieveSuspense<
  TData = Awaited<ReturnType<typeof invitationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof invitationsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInvitationsRetrieveSuspense<
  TData = Awaited<ReturnType<typeof invitationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof invitationsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useInvitationsRetrieveSuspense<
  TData = Awaited<ReturnType<typeof invitationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof invitationsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getInvitationsRetrieveSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteInvitation = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>(
    { url: `/api/v1/invitations/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteInvitationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteInvitation>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteInvitation>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteInvitation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteInvitation>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteInvitation(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteInvitation>>
>;

export type DeleteInvitationMutationError = ErrorType<unknown>;

export const useDeleteInvitation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteInvitation>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteInvitation>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteInvitationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const acceptInvitation = (
  invitationAccept: InvitationAccept,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Member>(
    {
      url: `/api/v1/invitations/accept`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: invitationAccept,
      signal,
    },
    options,
  );
};

export const getAcceptInvitationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptInvitation>>,
    TError,
    { data: InvitationAccept },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof acceptInvitation>>,
  TError,
  { data: InvitationAccept },
  TContext
> => {
  const mutationKey = ["acceptInvitation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acceptInvitation>>,
    { data: InvitationAccept }
  > = (props) => {
    const { data } = props ?? {};

    return acceptInvitation(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AcceptInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof acceptInvitation>>
>;
export type AcceptInvitationMutationBody = InvitationAccept;
export type AcceptInvitationMutationError = ErrorType<unknown>;

export const useAcceptInvitation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof acceptInvitation>>,
      TError,
      { data: InvitationAccept },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof acceptInvitation>>,
  TError,
  { data: InvitationAccept },
  TContext
> => {
  const mutationOptions = getAcceptInvitationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
