/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type {
  PaginatedPaymentList,
  Payment,
  PaymentRecord,
  PaymentsListParams,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const paymentsList = (
  params?: PaymentsListParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedPaymentList>(
    { url: `/api/v1/payments`, method: "GET", params, signal },
    options,
  );
};

export const getPaymentsListQueryKey = (params?: PaymentsListParams) => {
  return [`/api/v1/payments`, ...(params ? [params] : [])] as const;
};

export const getPaymentsListQueryOptions = <
  TData = Awaited<ReturnType<typeof paymentsList>>,
  TError = ErrorType<unknown>,
>(
  params?: PaymentsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paymentsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPaymentsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentsList>>> = ({
    signal,
  }) => paymentsList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof paymentsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PaymentsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof paymentsList>>
>;
export type PaymentsListQueryError = ErrorType<unknown>;

export function usePaymentsList<
  TData = Awaited<ReturnType<typeof paymentsList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | PaymentsListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paymentsList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsList>>,
          TError,
          Awaited<ReturnType<typeof paymentsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePaymentsList<
  TData = Awaited<ReturnType<typeof paymentsList>>,
  TError = ErrorType<unknown>,
>(
  params?: PaymentsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paymentsList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsList>>,
          TError,
          Awaited<ReturnType<typeof paymentsList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePaymentsList<
  TData = Awaited<ReturnType<typeof paymentsList>>,
  TError = ErrorType<unknown>,
>(
  params?: PaymentsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paymentsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function usePaymentsList<
  TData = Awaited<ReturnType<typeof paymentsList>>,
  TError = ErrorType<unknown>,
>(
  params?: PaymentsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paymentsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPaymentsListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPaymentsListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof paymentsList>>,
  TError = ErrorType<unknown>,
>(
  params?: PaymentsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof paymentsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPaymentsListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof paymentsList>>> = ({
    signal,
  }) => paymentsList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof paymentsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PaymentsListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof paymentsList>>
>;
export type PaymentsListSuspenseQueryError = ErrorType<unknown>;

export function usePaymentsListSuspense<
  TData = Awaited<ReturnType<typeof paymentsList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | PaymentsListParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof paymentsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePaymentsListSuspense<
  TData = Awaited<ReturnType<typeof paymentsList>>,
  TError = ErrorType<unknown>,
>(
  params?: PaymentsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof paymentsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePaymentsListSuspense<
  TData = Awaited<ReturnType<typeof paymentsList>>,
  TError = ErrorType<unknown>,
>(
  params?: PaymentsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof paymentsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function usePaymentsListSuspense<
  TData = Awaited<ReturnType<typeof paymentsList>>,
  TError = ErrorType<unknown>,
>(
  params?: PaymentsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof paymentsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPaymentsListSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const recordPayment = (
  paymentRecord: PaymentRecord,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Payment>(
    {
      url: `/api/v1/payments`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: paymentRecord,
      signal,
    },
    options,
  );
};

export const getRecordPaymentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recordPayment>>,
    TError,
    { data: PaymentRecord },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recordPayment>>,
  TError,
  { data: PaymentRecord },
  TContext
> => {
  const mutationKey = ["recordPayment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recordPayment>>,
    { data: PaymentRecord }
  > = (props) => {
    const { data } = props ?? {};

    return recordPayment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecordPaymentMutationResult = NonNullable<
  Awaited<ReturnType<typeof recordPayment>>
>;
export type RecordPaymentMutationBody = PaymentRecord;
export type RecordPaymentMutationError = ErrorType<unknown>;

export const useRecordPayment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recordPayment>>,
      TError,
      { data: PaymentRecord },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recordPayment>>,
  TError,
  { data: PaymentRecord },
  TContext
> => {
  const mutationOptions = getRecordPaymentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const paymentsRetrieve = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Payment>(
    { url: `/api/v1/payments/${id}`, method: "GET", signal },
    options,
  );
};

export const getPaymentsRetrieveQueryKey = (id?: string) => {
  return [`/api/v1/payments/${id}`] as const;
};

export const getPaymentsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof paymentsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof paymentsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPaymentsRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof paymentsRetrieve>>
  > = ({ signal }) => paymentsRetrieve(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof paymentsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PaymentsRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof paymentsRetrieve>>
>;
export type PaymentsRetrieveQueryError = ErrorType<unknown>;

export function usePaymentsRetrieve<
  TData = Awaited<ReturnType<typeof paymentsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof paymentsRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof paymentsRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePaymentsRetrieve<
  TData = Awaited<ReturnType<typeof paymentsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof paymentsRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof paymentsRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePaymentsRetrieve<
  TData = Awaited<ReturnType<typeof paymentsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof paymentsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function usePaymentsRetrieve<
  TData = Awaited<ReturnType<typeof paymentsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof paymentsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPaymentsRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPaymentsRetrieveSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof paymentsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof paymentsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPaymentsRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof paymentsRetrieve>>
  > = ({ signal }) => paymentsRetrieve(id, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof paymentsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PaymentsRetrieveSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof paymentsRetrieve>>
>;
export type PaymentsRetrieveSuspenseQueryError = ErrorType<unknown>;

export function usePaymentsRetrieveSuspense<
  TData = Awaited<ReturnType<typeof paymentsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof paymentsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePaymentsRetrieveSuspense<
  TData = Awaited<ReturnType<typeof paymentsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof paymentsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePaymentsRetrieveSuspense<
  TData = Awaited<ReturnType<typeof paymentsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof paymentsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function usePaymentsRetrieveSuspense<
  TData = Awaited<ReturnType<typeof paymentsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof paymentsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPaymentsRetrieveSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
