/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { AccountSubscription } from "./accountSubscription";
import type { BusinessProfile } from "./businessProfile";
import type { CountryEnum } from "./countryEnum";
import type { CurrencyEnum } from "./currencyEnum";
import type { LanguageEnum } from "./languageEnum";
import type { TaxId } from "./taxId";

export interface Account {
  id: string;
  name: string;
  email: string;
  country: CountryEnum;
  default_currency: CurrencyEnum;
  language: LanguageEnum;
  /** @nullable */
  invoice_footer: string | null;
  /** @nullable */
  invoice_numbering_system_id: string | null;
  /** @nullable */
  credit_note_numbering_system_id: string | null;
  /** @minimum 0 */
  net_payment_term: number;
  metadata: unknown;
  /** @nullable */
  subscription: AccountSubscription;
  /** @nullable */
  logo_id: string | null;
  /** @nullable */
  logo_url: string | null;
  readonly tax_ids: readonly TaxId[];
  default_business_profile: BusinessProfile;
  created_at: string;
  /** @nullable */
  updated_at: string | null;
}
