/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { AccountSubscription } from "./accountSubscription";
import type { Address } from "./address";
import type { CountryEnum } from "./countryEnum";
import type { CurrencyEnum } from "./currencyEnum";
import type { TaxId } from "./taxId";

export interface Account {
  id: string;
  name: string;
  /** @nullable */
  legal_name: string | null;
  /** @nullable */
  legal_number: string | null;
  email: string;
  /** @nullable */
  phone: string | null;
  address: Address;
  country: CountryEnum;
  default_currency: CurrencyEnum;
  /** @nullable */
  invoice_footer: string | null;
  /** @nullable */
  invoice_numbering_system_id: string | null;
  /** @nullable */
  credit_note_numbering_system_id: string | null;
  net_payment_term: number;
  metadata: unknown;
  /** @nullable */
  subscription: AccountSubscription;
  /** @nullable */
  logo_id: string | null;
  /** @nullable */
  logo_url: string | null;
  readonly tax_ids: readonly TaxId[];
  created_at: string;
  /** @nullable */
  updated_at: string | null;
}
