/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CountryEnum } from "./countryEnum";
import type { CurrencyEnum } from "./currencyEnum";
import type { LanguageEnum } from "./languageEnum";

export interface AccountUpdate {
  /** @maxLength 255 */
  name?: string;
  /** @maxLength 255 */
  email?: string;
  country?: CountryEnum;
  default_currency?: CurrencyEnum;
  language?: LanguageEnum;
  /**
   * @maxLength 255
   * @nullable
   */
  invoice_footer?: string | null;
  /** @nullable */
  invoice_numbering_system_id?: string | null;
  /** @nullable */
  credit_note_numbering_system_id?: string | null;
  /** @minimum 0 */
  net_payment_term?: number;
  metadata?: unknown;
  /** @nullable */
  logo_id?: string | null;
  default_business_profile_id?: string;
}
