/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { AccountConfigurationLoginMethodsItem } from "./accountConfigurationLoginMethodsItem";

/**
 * Configuration of the Django `allauth.account` app.

 */
export interface AccountConfiguration {
  login_methods?: AccountConfigurationLoginMethodsItem[];
  is_open_for_signup: boolean;
  email_verification_by_code_enabled: boolean;
  login_by_code_enabled: boolean;
  password_reset_by_code_enabled?: boolean;
}
