/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { AccountBusinessProfileAddress } from "./accountBusinessProfileAddress";
import type { TaxId } from "./taxId";

export interface AccountBusinessProfile {
  id: string;
  /** @nullable */
  legal_name: string | null;
  /** @nullable */
  legal_number: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  address: AccountBusinessProfileAddress;
  readonly tax_ids: readonly TaxId[];
  created_at: string;
  /** @nullable */
  updated_at: string | null;
}
