/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { RecoveryCodesAuthenticator } from "./recoveryCodesAuthenticator";
import type { TOTPAuthenticator } from "./tOTPAuthenticator";
import type { WebAuthnAuthenticator } from "./webAuthnAuthenticator";

export type AuthenticatorListItem =
  | TOTPAuthenticator
  | RecoveryCodesAuthenticator
  | WebAuthnAuthenticator;
