/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { AuthenticationMethodOneOfFiveMethod } from "./authenticationMethodOneOfFiveMethod";
import type { ProviderAccountID } from "./providerAccountID";
import type { ProviderID } from "./providerID";
import type { Timestamp } from "./timestamp";

export type AuthenticationMethodOneOfFive = {
  method: AuthenticationMethodOneOfFiveMethod;
  at: Timestamp;
  provider: ProviderID;
  uid: ProviderAccountID;
};
