/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { AuthenticatedMetaAllOf } from "./authenticatedMetaAllOf";
import type { BaseAuthenticationMeta } from "./baseAuthenticationMeta";

export type AuthenticatedMeta = BaseAuthenticationMeta & AuthenticatedMetaAllOf;
