/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * Metadata available in an re-authentication related response.

 */
export type AuthenticatedMetaAllOf = {
  is_authenticated: boolean;
};
