/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { AuthenticationMethodOneOfThreeMethod } from "./authenticationMethodOneOfThreeMethod";
import type { Timestamp } from "./timestamp";

export type AuthenticationMethodOneOfThree = {
  method: AuthenticationMethodOneOfThreeMethod;
  at: Timestamp;
  reauthenticated: boolean;
};
