/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { AuthenticationMetaAllOf } from "./authenticationMetaAllOf";
import type { BaseAuthenticationMeta } from "./baseAuthenticationMeta";

export type AuthenticationMeta = BaseAuthenticationMeta &
  AuthenticationMetaAllOf;
