/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { AuthenticatedResponse } from "./authenticatedResponse";

/**
 * Authenticated by password and 2FA.

 */
export type AuthenticatedByPasswordAnd2FAResponse = AuthenticatedResponse;
