/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { AuthenticationMeta } from "./authenticationMeta";
import type { AuthenticationResponseData } from "./authenticationResponseData";
import type { AuthenticationResponseStatus } from "./authenticationResponseStatus";

/**
 * An authentication related response.

 */
export interface AuthenticationResponse {
  status: AuthenticationResponseStatus;
  data: AuthenticationResponseData;
  meta: AuthenticationMeta;
}
