/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of authenticator.

 */
export type AuthenticatorType =
  (typeof AuthenticatorType)[keyof typeof AuthenticatorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthenticatorType = {
  recovery_codes: "recovery_codes",
  totp: "totp",
} as const;
