/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { BusinessProfileUpdateAddress } from "./businessProfileUpdateAddress";

export interface BusinessProfileUpdate {
  /**
   * @maxLength 255
   * @nullable
   */
  legal_name?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  legal_number?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  email?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  phone?: string | null;
  /** @nullable */
  address?: BusinessProfileUpdateAddress;
}
