/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Password } from "./password";

export type ChangePasswordBody = {
  current_password?: Password;
  /** The current password.
   */
  new_password: string;
};
