/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * The client ID (in case of OAuth2 or OpenID Connect based providers)

 */
export type ClientID = string;
