/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `internal` - Internal
 * `public` - Public
 */
export type CommentVisibilityEnum =
  (typeof CommentVisibilityEnum)[keyof typeof CommentVisibilityEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommentVisibilityEnum = {
  internal: "internal",
  public: "public",
} as const;
