/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export interface CommentAuthor {
  id: number;
  readonly name: string;
  /** @nullable */
  avatar_url: string | null;
}
