/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CommentAuthor } from "./commentAuthor";
import type { CommentVisibilityEnum } from "./commentVisibilityEnum";

export interface Comment {
  id: string;
  /** @maxLength 2048 */
  content: string;
  visibility: CommentVisibilityEnum;
  created_at: string;
  author: CommentAuthor;
}
