/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Plan } from "./plan";

export interface Config {
  is_billing_enabled: boolean;
  /** @maxLength 100 */
  current_plan_code: string;
  plans: Plan[];
}
