/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { ConfigurationResponseData } from "./configurationResponseData";
import type { StatusOK } from "./statusOK";

export interface ConfigurationResponse {
  data: ConfigurationResponseData;
  status: StatusOK;
}
