/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CouponCreateCurrency } from "./couponCreateCurrency";

export interface CouponCreate {
  /** @maxLength 255 */
  name?: string;
  /** @nullable */
  currency?: CouponCreateCurrency;
  /**
   * @nullable
   * @pattern ^-?\d{0,17}(?:\.\d{0,2})?$
   */
  amount?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,3}(?:\.\d{0,2})?$
   */
  percentage?: string | null;
}
