/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CreditNoteReasonEnum } from "./creditNoteReasonEnum";
import type { DeliveryMethodEnum } from "./deliveryMethodEnum";

export interface CreditNoteUpdate {
  /**
   * @maxLength 255
   * @nullable
   */
  number?: string | null;
  /** @nullable */
  numbering_system_id?: string | null;
  reason?: CreditNoteReasonEnum;
  metadata?: unknown;
  /**
   * @maxLength 500
   * @nullable
   */
  description?: string | null;
  delivery_method?: DeliveryMethodEnum;
  recipients?: string[];
}
