/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export interface CreditNoteLineUpdate {
  /**
   * @minimum 1
   * @nullable
   */
  quantity?: number | null;
  /** @maxLength 255 */
  description?: string;
  /**
   * @nullable
   * @pattern ^-?\d{0,17}(?:\.\d{0,2})?$
   */
  unit_amount?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,17}(?:\.\d{0,2})?$
   */
  amount?: string | null;
}
