/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CreditNoteAccount } from "./creditNoteAccount";
import type { CreditNoteCustomer } from "./creditNoteCustomer";
import type { CreditNoteLine } from "./creditNoteLine";
import type { CreditNotePaymentProvider } from "./creditNotePaymentProvider";
import type { CreditNoteReasonEnum } from "./creditNoteReasonEnum";
import type { CreditNoteStatusEnum } from "./creditNoteStatusEnum";
import type { CreditNoteTax } from "./creditNoteTax";
import type { CreditNoteTaxBreakdownItem } from "./creditNoteTaxBreakdownItem";
import type { CurrencyEnum } from "./currencyEnum";
import type { DeliveryMethodEnum } from "./deliveryMethodEnum";

export interface CreditNote {
  id: string;
  invoice_id: string;
  status: CreditNoteStatusEnum;
  reason: CreditNoteReasonEnum;
  /** @nullable */
  readonly number: string | null;
  /** @nullable */
  numbering_system_id: string | null;
  currency: CurrencyEnum;
  /** @nullable */
  issue_date: string | null;
  metadata: unknown;
  /** @nullable */
  description: string | null;
  delivery_method: DeliveryMethodEnum;
  recipients: string[];
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  subtotal_amount: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  total_amount_excluding_tax: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  total_tax_amount: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  total_amount: string;
  /** @nullable */
  payment_provider: CreditNotePaymentProvider;
  created_at: string;
  /** @nullable */
  updated_at: string | null;
  /** @nullable */
  issued_at: string | null;
  /** @nullable */
  voided_at: string | null;
  /** @nullable */
  pdf_id: string | null;
  readonly customer: CreditNoteCustomer;
  readonly account: CreditNoteAccount;
  readonly lines: readonly CreditNoteLine[];
  readonly taxes: readonly CreditNoteTax[];
  readonly tax_breakdown: readonly CreditNoteTaxBreakdownItem[];
}
