/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Address } from "./address";
import type { TaxId } from "./taxId";

export interface CreditNoteCustomer {
  id: string;
  name: string;
  /** @nullable */
  legal_name: string | null;
  /** @nullable */
  legal_number: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  description: string | null;
  billing_address: Address;
  shipping_address: Address;
  /** @nullable */
  logo_id: string | null;
  readonly tax_ids: readonly TaxId[];
}
