/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `duplicated_charge` - Duplicated Charge
 * `product_unsatisfactory` - Product Unsatisfactory
 * `order_change` - Order Change
 * `order_cancellation` - Order Cancellation
 * `fraudulent_charge` - Fraudulent Charge
 * `other` - Other
 */
export type CreditNoteReasonEnum =
  (typeof CreditNoteReasonEnum)[keyof typeof CreditNoteReasonEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreditNoteReasonEnum = {
  duplicated_charge: "duplicated_charge",
  product_unsatisfactory: "product_unsatisfactory",
  order_change: "order_change",
  order_cancellation: "order_cancellation",
  fraudulent_charge: "fraudulent_charge",
  other: "other",
} as const;
