/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { BillingProfile } from "./billingProfile";
import type { CustomerDefaultShippingProfile } from "./customerDefaultShippingProfile";

export interface Customer {
  id: string;
  account_id: string;
  name: string;
  /** @nullable */
  description: string | null;
  metadata: unknown;
  default_billing_profile: BillingProfile;
  /** @nullable */
  default_shipping_profile: CustomerDefaultShippingProfile;
  /** @nullable */
  logo_id: string | null;
  /** @nullable */
  logo_url: string | null;
  created_at: string;
  /** @nullable */
  updated_at: string | null;
}
