/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Address } from "./address";
import type { CustomerCurrency } from "./customerCurrency";
import type { TaxId } from "./taxId";
import type { TaxRate } from "./taxRate";

export interface Customer {
  id: string;
  account_id: string;
  name: string;
  /** @nullable */
  legal_name: string | null;
  /** @nullable */
  legal_number: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  currency: CustomerCurrency;
  /** @nullable */
  net_payment_term: number | null;
  /** @nullable */
  invoice_numbering_system_id: string | null;
  /** @nullable */
  credit_note_numbering_system_id: string | null;
  /** @nullable */
  description: string | null;
  metadata: unknown;
  billing_address: Address;
  shipping_address: Address;
  readonly tax_rates: readonly TaxRate[];
  readonly tax_ids: readonly TaxId[];
  /** @nullable */
  logo_id: string | null;
  /** @nullable */
  logo_url: string | null;
  created_at: string;
  /** @nullable */
  updated_at: string | null;
}
