/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerBillingProfileCreate } from "./customerBillingProfileCreate";
import type { CustomerCreateShippingProfile } from "./customerCreateShippingProfile";

export interface CustomerCreate {
  /** @maxLength 255 */
  name: string;
  billing_profile?: CustomerBillingProfileCreate;
  /** @nullable */
  shipping_profile?: CustomerCreateShippingProfile;
  /**
   * @maxLength 600
   * @nullable
   */
  description?: string | null;
  metadata?: unknown;
  /** @nullable */
  logo_id?: string | null;
}
