/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerCreateBillingAddress } from "./customerCreateBillingAddress";
import type { CustomerCreateCurrency } from "./customerCreateCurrency";
import type { CustomerCreateShippingAddress } from "./customerCreateShippingAddress";

export interface CustomerCreate {
  /** @maxLength 255 */
  name: string;
  /**
   * @maxLength 255
   * @nullable
   */
  legal_name?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  legal_number?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  email?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  phone?: string | null;
  /**
   * @maxLength 600
   * @nullable
   */
  description?: string | null;
  /** @nullable */
  currency?: CustomerCreateCurrency;
  /** @nullable */
  net_payment_term?: number | null;
  /** @nullable */
  invoice_numbering_system_id?: string | null;
  /** @nullable */
  credit_note_numbering_system_id?: string | null;
  metadata?: unknown;
  /** @nullable */
  billing_address?: CustomerCreateBillingAddress;
  /** @nullable */
  shipping_address?: CustomerCreateShippingAddress;
  /** @nullable */
  logo_id?: string | null;
}
