/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { BillingProfile } from "./billingProfile";
import type { CustomerCurrency } from "./customerCurrency";
import type { CustomerDefaultShippingProfile } from "./customerDefaultShippingProfile";
import type { CustomerLanguage } from "./customerLanguage";
import type { TaxId } from "./taxId";
import type { TaxRate } from "./taxRate";

export interface Customer {
  id: string;
  account_id: string;
  name: string;
  /** @nullable */
  description: string | null;
  metadata: unknown;
  /** @nullable */
  currency: CustomerCurrency;
  /** @nullable */
  language: CustomerLanguage;
  /**
   * @minimum 0
   * @nullable
   */
  net_payment_term: number | null;
  /** @nullable */
  invoice_numbering_system_id: string | null;
  /** @nullable */
  credit_note_numbering_system_id: string | null;
  default_billing_profile: BillingProfile;
  /** @nullable */
  default_shipping_profile: CustomerDefaultShippingProfile;
  /** @nullable */
  logo_id: string | null;
  /** @nullable */
  logo_url: string | null;
  readonly tax_rates: readonly TaxRate[];
  readonly tax_ids: readonly TaxId[];
  created_at: string;
  /** @nullable */
  updated_at: string | null;
}
