/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerBillingProfileCreateAddress } from "./customerBillingProfileCreateAddress";
import type { CustomerBillingProfileCreateCurrency } from "./customerBillingProfileCreateCurrency";
import type { CustomerBillingProfileCreateLanguage } from "./customerBillingProfileCreateLanguage";

export interface CustomerBillingProfileCreate {
  /**
   * @maxLength 255
   * @nullable
   */
  legal_name?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  legal_number?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  email?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  phone?: string | null;
  /** @nullable */
  address?: CustomerBillingProfileCreateAddress;
  /** @nullable */
  currency?: CustomerBillingProfileCreateCurrency;
  /** @nullable */
  language?: CustomerBillingProfileCreateLanguage;
  /**
   * @minimum 0
   * @nullable
   */
  net_payment_term?: number | null;
  /** @nullable */
  invoice_numbering_system_id?: string | null;
  /** @nullable */
  credit_note_numbering_system_id?: string | null;
  tax_rates?: string[];
}
