/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export interface CustomerUpdate {
  /** @maxLength 255 */
  name?: string;
  /**
   * @maxLength 600
   * @nullable
   */
  description?: string | null;
  metadata?: unknown;
  /** @nullable */
  logo_id?: string | null;
  default_billing_profile_id?: string;
  default_shipping_profile_id?: string;
}
