/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerShippingProfileCreateAddress } from "./customerShippingProfileCreateAddress";

export interface CustomerShippingProfileCreate {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  address?: CustomerShippingProfileCreateAddress;
}
