/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CurrencyEnum } from "./currencyEnum";
import type { DefaultPriceCreateMetadata } from "./defaultPriceCreateMetadata";

export interface DefaultPriceCreate {
  currency: CurrencyEnum;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  amount: string;
  /** @nullable */
  metadata: DefaultPriceCreateMetadata;
  /**
   * @maxLength 255
   * @nullable
   */
  code: string | null;
}
