/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `manual` - Manual
 * `automatic` - Automatic
 */
export type DeliveryMethodEnum =
  (typeof DeliveryMethodEnum)[keyof typeof DeliveryMethodEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliveryMethodEnum = {
  manual: "manual",
  automatic: "automatic",
} as const;
