/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { EmailVerificationInfo } from "./emailVerificationInfo";

/**
 * Email verification information.
 */
export type EmailVerificationInfoResponse = EmailVerificationInfo;
