/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export type EmailVerificationInfoMeta = {
  is_authenticating: boolean;
};
