/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Email } from "./email";
import type { User } from "./user";

export type EmailVerificationInfoData = {
  email: Email;
  user: User;
};
