/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `product_image` - Product Image
 * `invoice_pdf` - Invoice Pdf
 * `quote_pdf` - Quote Pdf
 * `credit_note_pdf` - Credit Note Pdf
 * `account_logo` - Account Logo
 * `profile_avatar` - Profile Avatar
 * `customer_logo` - Customer Logo
 */
export type FilePurposeEnum =
  (typeof FilePurposeEnum)[keyof typeof FilePurposeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FilePurposeEnum = {
  product_image: "product_image",
  invoice_pdf: "invoice_pdf",
  quote_pdf: "quote_pdf",
  credit_note_pdf: "credit_note_pdf",
  account_logo: "account_logo",
  profile_avatar: "profile_avatar",
  customer_logo: "customer_logo",
} as const;
