/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { FilePurposeEnum } from "./filePurposeEnum";

export interface File {
  id: string;
  /** @nullable */
  account_id: string | null;
  purpose: FilePurposeEnum;
  url: string;
  filename: string;
  size: number;
  content_type: string;
  created_at: string;
}
