/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export type ForbiddenResponseStatus =
  (typeof ForbiddenResponseStatus)[keyof typeof ForbiddenResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ForbiddenResponseStatus = {
  NUMBER_403: 403,
} as const;
