/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { InvitationStatusEnum } from "./invitationStatusEnum";

export interface Invitation {
  id: string;
  email: string;
  status: InvitationStatusEnum;
  created_at: string;
  /** @nullable */
  accepted_at: string | null;
}
