/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Coupon } from "./coupon";
import type { InvoiceDiscount } from "./invoiceDiscount";
import type { InvoiceTax } from "./invoiceTax";
import type { TaxRate } from "./taxRate";

export interface InvoiceLine {
  id: string;
  description: string;
  quantity: number;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  unit_amount: string;
  /** @nullable */
  price_id: string | null;
  /** @nullable */
  product_id: string | null;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  readonly amount: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  readonly subtotal_amount: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  readonly total_discount_amount: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  readonly total_excluding_tax_amount: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  readonly total_tax_amount: string;
  /** @pattern ^-?\d{0,3}(?:\.\d{0,2})?$ */
  readonly total_tax_rate: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  readonly total_amount: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  readonly total_credit_amount: string;
  readonly credit_quantity: number;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  readonly outstanding_amount: string;
  readonly outstanding_quantity: number;
  coupons: Coupon[];
  readonly discounts: readonly InvoiceDiscount[];
  readonly total_discounts: readonly InvoiceDiscount[];
  tax_rates: TaxRate[];
  readonly taxes: readonly InvoiceTax[];
  readonly total_taxes: readonly InvoiceTax[];
}
