/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export interface InvoiceLineTax {
  id: string;
  tax_rate_id: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @pattern ^-?\d{0,3}(?:\.\d{0,2})?$ */
  rate: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  amount: string;
}
