/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export interface InvoiceTax {
  tax_rate_id: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  amount: string;
}
