/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export interface InvoiceShippingAdd {
  shipping_rate_id: string;
  /** @nullable */
  shipping_profile_id?: string | null;
  tax_rates?: string[];
}
