/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { DeliveryMethodEnum } from "./deliveryMethodEnum";
import type { InvoiceCreateCurrency } from "./invoiceCreateCurrency";
import type { InvoiceCreateCustomFields } from "./invoiceCreateCustomFields";
import type { InvoiceCreateMetadata } from "./invoiceCreateMetadata";
import type { InvoiceCreatePaymentProvider } from "./invoiceCreatePaymentProvider";
import type { InvoiceCreateShipping } from "./invoiceCreateShipping";
import type { TaxBehaviorEnum } from "./taxBehaviorEnum";

export interface InvoiceCreate {
  customer_id: string;
  /**
   * @maxLength 255
   * @nullable
   */
  number?: string | null;
  /** @nullable */
  numbering_system_id?: string | null;
  /** @nullable */
  currency?: InvoiceCreateCurrency;
  tax_behavior?: TaxBehaviorEnum;
  /** @nullable */
  issue_date?: string | null;
  /** @nullable */
  due_date?: string | null;
  /**
   * @minimum 0
   * @nullable
   */
  net_payment_term?: number | null;
  /** @nullable */
  metadata?: InvoiceCreateMetadata;
  /** @nullable */
  custom_fields?: InvoiceCreateCustomFields;
  /**
   * @maxLength 600
   * @nullable
   */
  footer?: string | null;
  /**
   * @maxLength 600
   * @nullable
   */
  description?: string | null;
  /** @nullable */
  payment_provider?: InvoiceCreatePaymentProvider;
  /** @nullable */
  payment_connection_id?: string | null;
  delivery_method?: DeliveryMethodEnum;
  recipients?: string[];
  tax_rates?: string[];
  coupons?: string[];
  /** @nullable */
  shipping?: InvoiceCreateShipping;
}
