/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { InvoiceShippingAddress } from "./invoiceShippingAddress";
import type { InvoiceTax } from "./invoiceTax";
import type { TaxRate } from "./taxRate";

export interface InvoiceShipping {
  /** @nullable */
  name: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  address: InvoiceShippingAddress;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  amount: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  total_excluding_tax_amount: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  total_tax_amount: string;
  /** @pattern ^-?\d{0,3}(?:\.\d{0,2})?$ */
  total_tax_rate: string;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  total_amount: string;
  /** @nullable */
  shipping_rate_id: string | null;
  tax_rates: TaxRate[];
  total_taxes: InvoiceTax[];
}
