/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { DeliveryMethodEnum } from "./deliveryMethodEnum";
import type { InvoiceRevisionCreateCurrency } from "./invoiceRevisionCreateCurrency";
import type { InvoiceRevisionCreateMetadata } from "./invoiceRevisionCreateMetadata";
import type { InvoiceRevisionCreatePaymentProvider } from "./invoiceRevisionCreatePaymentProvider";
import type { InvoiceRevisionCreateShipping } from "./invoiceRevisionCreateShipping";
import type { TaxBehaviorEnum } from "./taxBehaviorEnum";

export interface InvoiceRevisionCreate {
  billing_profile_id?: string;
  business_profile_id?: string;
  /**
   * @maxLength 255
   * @nullable
   */
  number?: string | null;
  /** @nullable */
  numbering_system_id?: string | null;
  /** @nullable */
  currency?: InvoiceRevisionCreateCurrency;
  tax_behavior?: TaxBehaviorEnum;
  /** @nullable */
  issue_date?: string | null;
  /** @nullable */
  due_date?: string | null;
  /**
   * @minimum 0
   * @nullable
   */
  net_payment_term?: number | null;
  /** @nullable */
  metadata?: InvoiceRevisionCreateMetadata;
  /** @nullable */
  payment_provider?: InvoiceRevisionCreatePaymentProvider;
  /** @nullable */
  payment_connection_id?: string | null;
  delivery_method?: DeliveryMethodEnum;
  recipients?: string[];
  tax_rates?: string[];
  coupons?: string[];
  /** @nullable */
  shipping?: InvoiceRevisionCreateShipping;
}
