/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export type InvoicesListParams = {
  created_at_after?: string;
  created_at_before?: string;
  /**
   * Multiple values may be separated by commas.
   */
  currency?: string[];
  customer_id?: string;
  due_date_after?: string;
  due_date_before?: string;
  issue_date_after?: string;
  issue_date_before?: string;
  latest_revision_id?: string;
  numbering_system_id?: string;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  outstanding_amount_max?: number;
  outstanding_amount_min?: number;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * Number of results to return per page.
   */
  page_size?: number;
  previous_revision_id?: string;
  product_id?: string;
  /**
   * A search term.
   */
  search?: string;
  /**
   * Multiple values may be separated by commas.
   */
  status?: string[];
  subtotal_amount_max?: number;
  subtotal_amount_min?: number;
  total_amount_max?: number;
  total_amount_min?: number;
  total_paid_amount_max?: number;
  total_paid_amount_min?: number;
};
