/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `en-us` - English
 * `en-gb` - British English
 * `en-au` - Australian English
 * `de` - German
 * `fr` - French
 * `it` - Italian
 * `es` - Spanish
 */
export type LanguageEnum = (typeof LanguageEnum)[keyof typeof LanguageEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LanguageEnum = {
  "en-us": "en-us",
  "en-gb": "en-gb",
  "en-au": "en-au",
  de: "de",
  fr: "fr",
  it: "it",
  es: "es",
} as const;
