/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `invoice` - Invoice
 * `credit_note` - Credit Note
 * `quote` - Quote
 */
export type NumberingSystemAppliesToEnum =
  (typeof NumberingSystemAppliesToEnum)[keyof typeof NumberingSystemAppliesToEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NumberingSystemAppliesToEnum = {
  invoice: "invoice",
  credit_note: "credit_note",
  quote: "quote",
} as const;
