/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { NumberingSystemAppliesToEnum } from "./numberingSystemAppliesToEnum";
import type { NumberingSystemCreateResetInterval } from "./numberingSystemCreateResetInterval";

export interface NumberingSystemCreate {
  /** @maxLength 100 */
  template: string;
  /**
   * @maxLength 255
   * @nullable
   */
  description?: string | null;
  applies_to: NumberingSystemAppliesToEnum;
  /** @nullable */
  reset_interval?: NumberingSystemCreateResetInterval;
}
