/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { NumberingSystemAppliesToEnum } from "./numberingSystemAppliesToEnum";
import type { NumberingSystemResetIntervalEnum } from "./numberingSystemResetIntervalEnum";
import type { ProductCatalogStatusEnum } from "./productCatalogStatusEnum";

export interface NumberingSystem {
  id: string;
  /** @maxLength 100 */
  template: string;
  /** @nullable */
  description: string | null;
  applies_to: NumberingSystemAppliesToEnum;
  reset_interval: NumberingSystemResetIntervalEnum;
  status: ProductCatalogStatusEnum;
  created_at: string;
  /** @nullable */
  updated_at: string | null;
  /** @nullable */
  archived_at: string | null;
}
