/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `never` - Never
 * `weekly` - Weekly
 * `monthly` - Monthly
 * `quarterly` - Quarterly
 * `yearly` - Yearly
 */
export type NumberingSystemResetIntervalEnum =
  (typeof NumberingSystemResetIntervalEnum)[keyof typeof NumberingSystemResetIntervalEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NumberingSystemResetIntervalEnum = {
  never: "never",
  weekly: "weekly",
  monthly: "monthly",
  quarterly: "quarterly",
  yearly: "yearly",
} as const;
