/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { NumberingSystemUpdateResetInterval } from "./numberingSystemUpdateResetInterval";

export interface NumberingSystemUpdate {
  /** @maxLength 100 */
  template: string;
  /**
   * @maxLength 255
   * @nullable
   */
  description: string | null;
  /** @nullable */
  reset_interval: NumberingSystemUpdateResetInterval;
}
