/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CurrencyEnum } from "./currencyEnum";

export interface OverdueBalance {
  date: string;
  currency: CurrencyEnum;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  total_amount: string;
  invoice_ids: string[];
}
