/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { PasswordResetInfoResponseData } from "./passwordResetInfoResponseData";
import type { StatusOK } from "./statusOK";

export type PasswordResetInfoResponse = {
  status: StatusOK;
  data: PasswordResetInfoResponseData;
};
