/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `succeeded` - Succeeded
 * `pending` - Pending
 * `failed` - Failed
 * `rejected` - Rejected
 */
export type PaymentStatusEnum =
  (typeof PaymentStatusEnum)[keyof typeof PaymentStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentStatusEnum = {
  succeeded: "succeeded",
  pending: "pending",
  failed: "failed",
  rejected: "rejected",
} as const;
