/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { PhoneNumber } from "./phoneNumber";
import type { StatusAccepted } from "./statusAccepted";

export interface PhoneNumberChangeResponse {
  status: StatusAccepted;
  data: PhoneNumber[];
}
