/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { PlanFeature } from "./planFeature";
import type { PlanLimit } from "./planLimit";

export interface Plan {
  /** @maxLength 100 */
  name: string;
  /** @maxLength 100 */
  code: string;
  features: PlanFeature[];
  limits: PlanLimit[];
  /**
   * @maxLength 100
   * @nullable
   */
  price_id: string | null;
}
