/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Address } from "./address";
import type { PortalCustomerShippingProperty } from "./portalCustomerShippingProperty";
import type { TaxId } from "./taxId";

export interface PortalCustomer {
  id: string;
  name: string;
  /** @nullable */
  legal_name: string | null;
  /** @nullable */
  legal_number: string | null;
  /** @nullable */
  email: string | null;
  /** @nullable */
  phone: string | null;
  address: Address;
  /** @nullable */
  shipping: PortalCustomerShippingProperty;
  tax_ids: TaxId[];
}
