/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export type PreviewCreditNoteFormat =
  (typeof PreviewCreditNoteFormat)[keyof typeof PreviewCreditNoteFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreviewCreditNoteFormat = {
  email: "email",
  pdf: "pdf",
} as const;
