/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export type PreviewQuoteFormat =
  (typeof PreviewQuoteFormat)[keyof typeof PreviewQuoteFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreviewQuoteFormat = {
  email: "email",
  pdf: "pdf",
} as const;
