/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CurrencyEnum } from "./currencyEnum";
import type { PriceModelEnum } from "./priceModelEnum";
import type { PriceProduct } from "./priceProduct";
import type { PriceTier } from "./priceTier";

export interface Price {
  id: string;
  account_id: string;
  product: PriceProduct;
  currency: CurrencyEnum;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  amount?: string;
  model: PriceModelEnum;
  is_active: boolean;
  metadata: unknown;
  is_used: boolean;
  /**
   * @maxLength 255
   * @nullable
   */
  code: string | null;
  created_at: string;
  /** @nullable */
  updated_at: string | null;
  /** @nullable */
  archived_at: string | null;
  tiers: PriceTier[];
}
