/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CurrencyEnum } from "./currencyEnum";
import type { PriceTierInput } from "./priceTierInput";
import type { PriceUpdateMetadata } from "./priceUpdateMetadata";

export interface PriceUpdate {
  currency?: CurrencyEnum;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  amount?: string;
  /** @nullable */
  metadata?: PriceUpdateMetadata;
  /**
   * @maxLength 255
   * @nullable
   */
  code?: string | null;
  tiers?: PriceTierInput[];
}
