/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { PricesListStatus } from "./pricesListStatus";

export type PricesListParams = {
  created_at_after?: string;
  created_at_before?: string;
  currency?: string;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * Number of results to return per page.
   */
  page_size?: number;
  product_id?: string;
  /**
   * A search term.
   */
  search?: string;
  /**
   * * `active` - Active
   * `archived` - Archived
   */
  status?: PricesListStatus;
};
