/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { CurrencyEnum } from "./currencyEnum";
import type { PriceCreateMetadata } from "./priceCreateMetadata";
import type { PriceModelEnum } from "./priceModelEnum";
import type { PriceTierInput } from "./priceTierInput";

export interface PriceCreate {
  product_id: string;
  currency: CurrencyEnum;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  amount?: string;
  /** @nullable */
  metadata?: PriceCreateMetadata;
  /**
   * @maxLength 255
   * @nullable
   */
  code?: string | null;
  model?: PriceModelEnum;
  tiers?: PriceTierInput[];
}
