/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { PriceProductMetadata } from "./priceProductMetadata";
import type { ProductCatalogStatusEnum } from "./productCatalogStatusEnum";

export interface PriceProduct {
  id: string;
  /** @maxLength 255 */
  name: string;
  /** @maxLength 1000 */
  description: string;
  status: ProductCatalogStatusEnum;
  /** @nullable */
  default_price_id: string | null;
  /** @nullable */
  metadata: PriceProductMetadata;
  created_at: string;
  /** @nullable */
  updated_at: string | null;
  /** @nullable */
  archived_at: string | null;
}
