/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * The process to be executed when the user successfully
authenticates. When set to `login`, the user will be logged into the
account to which the provider account is connected, or if no such
account exists, a signup will occur. If set to `connect`, the provider
account will be connected to the list of provider accounts for the
currently authenticated user.

 */
export type Process = (typeof Process)[keyof typeof Process];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Process = {
  login: "login",
  connect: "connect",
} as const;
