/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export interface ProductUpdate {
  /** @maxLength 255 */
  name?: string;
  /**
   * @maxLength 600
   * @nullable
   */
  description?: string | null;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  image_id?: string | null;
  /** @nullable */
  default_price_id?: string | null;
  metadata?: unknown;
}
