/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { ProductDefaultPrice } from "./productDefaultPrice";

export interface Product {
  id: string;
  account_id: string;
  /** @maxLength 255 */
  name: string;
  /**
   * @maxLength 600
   * @nullable
   */
  description: string | null;
  is_active: boolean;
  /** @nullable */
  url: string | null;
  /** @nullable */
  image_url: string | null;
  /** @nullable */
  image_id: string | null;
  /** @nullable */
  default_price: ProductDefaultPrice;
  readonly prices_count: number;
  metadata: unknown;
  created_at: string;
  /** @nullable */
  updated_at: string | null;
}
