/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `active` - Active
 * `archived` - Archived
 */
export type ProductCatalogStatusEnum =
  (typeof ProductCatalogStatusEnum)[keyof typeof ProductCatalogStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductCatalogStatusEnum = {
  active: "active",
  archived: "archived",
} as const;
