/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { ProductCreateDefaultPrice } from "./productCreateDefaultPrice";
import type { ProductCreateMetadata } from "./productCreateMetadata";

export interface ProductCreate {
  /** @maxLength 255 */
  name: string;
  /**
   * @maxLength 600
   * @nullable
   */
  description?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  url?: string | null;
  /** @nullable */
  default_price?: ProductCreateDefaultPrice;
  /** @nullable */
  image_id?: string | null;
  /** @nullable */
  metadata?: ProductCreateMetadata;
}
