/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { ClientID } from "./clientID";

/**
 * The token.

 */
export type ProviderTokenToken = {
  client_id: ClientID;
  /** The ID token.
   */
  id_token?: string;
  /** The access token.
   */
  access_token?: string;
};
