/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Process } from "./process";
import type { ProviderID } from "./providerID";

export interface ProviderRedirect {
  provider: ProviderID;
  /** The URL to return to after the redirect flow is complete.
   */
  callback_url: string;
  process: Process;
}
