/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { EmailAddress } from "./emailAddress";
import type { ProviderAccount } from "./providerAccount";
import type { User } from "./user";

export type ProviderSignupResponseData = {
  email: EmailAddress[];
  account: ProviderAccount;
  user: User;
};
