/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { DeliveryMethodEnum } from "./deliveryMethodEnum";
import type { QuoteCreateCurrency } from "./quoteCreateCurrency";
import type { QuoteCreateCustomFields } from "./quoteCreateCustomFields";
import type { QuoteCreateMetadata } from "./quoteCreateMetadata";

export interface QuoteCreate {
  customer_id: string;
  /**
   * @maxLength 255
   * @nullable
   */
  number?: string | null;
  /** @nullable */
  numbering_system_id?: string | null;
  /** @nullable */
  currency?: QuoteCreateCurrency;
  /** @nullable */
  issue_date?: string | null;
  /** @nullable */
  metadata?: QuoteCreateMetadata;
  /** @nullable */
  custom_fields?: QuoteCreateCustomFields;
  /**
   * @maxLength 600
   * @nullable
   */
  footer?: string | null;
  /**
   * @maxLength 600
   * @nullable
   */
  description?: string | null;
  delivery_method?: DeliveryMethodEnum;
  recipients?: string[];
}
