/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Coupon } from "./coupon";

export interface QuoteDiscount {
  id: string;
  readonly coupon: Coupon;
  /** @pattern ^-?\d{0,17}(?:\.\d{0,2})?$ */
  amount: string;
}
