/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export type ReauthenticationResponseStatus =
  (typeof ReauthenticationResponseStatus)[keyof typeof ReauthenticationResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReauthenticationResponseStatus = {
  NUMBER_401: 401,
} as const;
