/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Authenticated } from "./authenticated";
import type { AuthenticatedMeta } from "./authenticatedMeta";
import type { ReauthenticationResponseStatus } from "./reauthenticationResponseStatus";

/**
 * A response indicating reauthentication is required.

 */
export interface ReauthenticationResponse {
  status: ReauthenticationResponseStatus;
  data: Authenticated;
  meta: AuthenticatedMeta;
}
