/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Reauthenticate } from "./reauthenticate";

/**
 * Reauthenticate.
 */
export type ReauthenticateBody = Reauthenticate;
