/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { RecoveryCodesAuthenticatorAllOfType } from "./recoveryCodesAuthenticatorAllOfType";

export type RecoveryCodesAuthenticatorAllOf = {
  /** The authenticator type.
   */
  type: RecoveryCodesAuthenticatorAllOfType;
  /** The total number of recovery codes that initially were available.
   */
  total_code_count: number;
  /** The number of recovery codes that are unused.
   */
  unused_code_count: number;
};
