/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

/**
 * The authenticator type.

 */
export type RecoveryCodesAuthenticatorAllOfType =
  (typeof RecoveryCodesAuthenticatorAllOfType)[keyof typeof RecoveryCodesAuthenticatorAllOfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecoveryCodesAuthenticatorAllOfType = {
  recovery_codes: "recovery_codes",
} as const;
