/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export type ServerErrorEnum =
  (typeof ServerErrorEnum)[keyof typeof ServerErrorEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServerErrorEnum = {
  server_error: "server_error",
} as const;
