/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { Timestamp } from "./timestamp";

export interface Session {
  user_agent: string;
  ip: string;
  created_at: Timestamp;
  is_current: boolean;
  id: number;
  last_seen_at?: Timestamp;
}
