/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { ProviderList } from "./providerList";

/**
 * Configuration of the Django `allauth.socialaccount` app.

 */
export interface SocialAccountConfiguration {
  providers: ProviderList;
}
