/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export type StatusOK = (typeof StatusOK)[keyof typeof StatusOK];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusOK = {
  NUMBER_200: 200,
} as const;
