/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export type StatusAccepted =
  (typeof StatusAccepted)[keyof typeof StatusAccepted];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusAccepted = {
  NUMBER_202: 202,
} as const;
