/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export interface StripeSubscription {
  price_id: string;
  started_at: string;
  /** @nullable */
  ended_at: string | null;
  /** @nullable */
  canceled_at: string | null;
  status: string;
}
