/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { TaxRateUpdateCountry } from "./taxRateUpdateCountry";

export interface TaxRateUpdate {
  /** @maxLength 255 */
  name?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  country?: TaxRateUpdateCountry;
}
