/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export type TOTPAuthenticatorNotFoundResponseMeta = {
  /** A TOTP secret that can be used to setup a new authenticator.
   */
  secret: string;
  /** otpauth URI from which a QR code can be generated and scanned by OTP clients.
   */
  totp_url: string;
};
