/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { StatusOK } from "./statusOK";
import type { TOTPAuthenticator } from "./tOTPAuthenticator";

export type TOTPAuthenticatorResponse = {
  status: StatusOK;
  data: TOTPAuthenticator;
};
