/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { AuthenticationResponse } from "./authenticationResponse";

/**
 * There is no authenticated session.

 */
export type UnauthenticatedResponse = AuthenticationResponse;
