/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */

export type ValidationErrorEnum =
  (typeof ValidationErrorEnum)[keyof typeof ValidationErrorEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidationErrorEnum = {
  validation_error: "validation_error",
} as const;
