/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { StatusOK } from "./statusOK";
import type { WebAuthnCredentialCreationOptions } from "./webAuthnCredentialCreationOptions";

export type WebAuthnCreationOptionsResponseResponse = {
  status: StatusOK;
  data: WebAuthnCredentialCreationOptions;
};
