/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { BaseAuthenticator } from "./baseAuthenticator";
import type { WebAuthnAuthenticatorAllOf } from "./webAuthnAuthenticatorAllOf";

export type WebAuthnAuthenticator = BaseAuthenticator &
  WebAuthnAuthenticatorAllOf;
