/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { WebAuthnCredentialRequestOptionsRequestOptions } from "./webAuthnCredentialRequestOptionsRequestOptions";

export interface WebAuthnCredentialRequestOptions {
  request_options: WebAuthnCredentialRequestOptionsRequestOptions;
}
