/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import type { StatusOK } from "./statusOK";
import type { WebAuthnAuthenticator } from "./webAuthnAuthenticator";

export type WebAuthnAuthenticatorResponse = {
  status: StatusOK;
  data: WebAuthnAuthenticator;
};
