# Generated by Django 5.2 on 2026-01-23 18:03

import uuid

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(null=True)),
                ("rejected_at", models.DateTimeField(null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("member", "Member"), ("owner", "Owner")], max_length=50)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255, null=True)),
                ("legal_number", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("default_currency", models.CharField(max_length=3)),
                ("invoice_footer", models.CharField(blank=True, max_length=600, null=True)),
                ("net_payment_term", models.IntegerField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_address",
                        to="addresses.address",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
