# Generated by Django 5.2 on 2025-11-02 13:24

import uuid

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("addresses", "0001_initial"),
        ("coupons", "0001_initial"),
        ("customers", "0002_initial"),
        ("files", "0002_initial"),
        ("numbering_systems", "0001_initial"),
        ("prices", "0002_initial"),
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255, null=True)),
                ("legal_number", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_account_address",
                        to="addresses.address",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_account_logo",
                        to="files.file",
                    ),
                ),
                ("tax_ids", models.ManyToManyField(related_name="invoice_accounts", to="taxes.taxid")),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceCustomer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255, null=True)),
                ("legal_number", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billing_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_customer_billing_address",
                        to="addresses.address",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_customer_logo",
                        to="files.file",
                    ),
                ),
                (
                    "shipping_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_customer_shipping_address",
                        to="addresses.address",
                    ),
                ),
                ("tax_ids", models.ManyToManyField(related_name="invoice_customers", to="taxes.taxid")),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=255, null=True)),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("open", "Open"), ("paid", "Paid"), ("voided", "Voided")],
                        max_length=50,
                    ),
                ),
                ("issue_date", models.DateField(null=True)),
                ("sell_date", models.DateField(null=True)),
                ("due_date", models.DateField(null=True)),
                ("net_payment_term", models.IntegerField(default=7)),
                ("footer", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "subtotal_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_discount_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount_excluding_tax",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("opened_at", models.DateTimeField(null=True)),
                ("paid_at", models.DateTimeField(null=True)),
                ("voided_at", models.DateTimeField(null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("custom_fields", models.JSONField(default=dict)),
                ("payment_provider", models.CharField(choices=[("stripe", "Stripe")], max_length=50, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="accounts.account"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="customers.customer"
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="latest_revision_sources",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "numbering_system",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="numbering_systems.numberingsystem",
                    ),
                ),
                (
                    "pdf",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_pdf",
                        to="files.file",
                    ),
                ),
                (
                    "previous_revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "account_on_invoice",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="invoices.invoiceaccount",
                    ),
                ),
                (
                    "customer_on_invoice",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="invoices.invoicecustomer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "unit_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount_excluding_tax",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_discount_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("total_tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="invoices.invoice"
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_lines",
                        to="prices.price",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceDiscount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_discounts",
                        to="coupons.coupon",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="discounts", to="invoices.invoice"
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="invoices.invoiceline",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTax",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255, null=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="taxes", to="invoices.invoice"
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="invoices.invoiceline",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_taxes",
                        to="taxes.taxrate",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["account_id", "number"], name="account_id_number_idx"),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "draft"),
                    models.Q(("number__isnull", False), models.Q(("number", ""), _negated=True)),
                    _connector="OR",
                ),
                name="invoice_number_required_if_not_draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("previous_revision__isnull", True),
                    models.Q(("previous_revision", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="invoice_cannot_reference_itself",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicediscount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_line__isnull", False)),
                fields=("invoice_line", "coupon"),
                name="unique_invoice_line_coupon",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicediscount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_line__isnull", True)),
                fields=("invoice", "coupon"),
                name="unique_invoice_coupon",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicetax",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_line__isnull", False), ("tax_rate__isnull", False)),
                fields=("invoice_line", "tax_rate"),
                name="unique_invoice_line_tax_rate",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicetax",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_line__isnull", True), ("tax_rate__isnull", False)),
                fields=("invoice", "tax_rate"),
                name="unique_invoice_tax_rate",
            ),
        ),
    ]
