# Generated by Django 5.2 on 2025-11-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("addresses", "0001_initial"),
        ("coupons", "0001_initial"),
        ("customers", "0002_initial"),
        ("invoices", "0001_initial"),
        ("numbering_systems", "0001_initial"),
        ("prices", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="accounts.account"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="customers.customer"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="numbering_system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="numbering_systems.numberingsystem",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceaccount",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_account_address",
                to="addresses.address",
            ),
        ),
        migrations.AlterField(
            model_name="invoicecustomer",
            name="billing_address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_customer_billing_address",
                to="addresses.address",
            ),
        ),
        migrations.AlterField(
            model_name="invoicecustomer",
            name="shipping_address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_customer_shipping_address",
                to="addresses.address",
            ),
        ),
        migrations.AlterField(
            model_name="invoicediscount",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoice_discounts", to="coupons.coupon"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="price",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="invoice_lines", to="prices.price"
            ),
        ),
    ]
