# Generated by Django 5.2 on 2025-12-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0005_invoice_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_connection_id",
            field=models.UUIDField(null=True),
        ),
    ]
