# Generated by Django 5.2 on 2026-01-08 16:42

import uuid
from decimal import Decimal

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0006_invoice_payment_connection_id"),
        ("shipping_rates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="shipping_amount",
            field=djmoney.models.fields.MoneyField(
                currency_field_name="currency", decimal_places=2, default=Decimal("0"), max_digits=19
            ),
        ),
        migrations.CreateModel(
            name="InvoiceShipping",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipping_rate",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="shipping_rates.shippingrate"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice",
                to="invoices.invoiceshipping",
            ),
        ),
        migrations.AddField(
            model_name="invoicetax",
            name="invoice_shipping",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taxes",
                to="invoices.invoiceshipping",
            ),
        ),
    ]
