# Generated by Django 5.2 on 2026-01-25 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0007_remove_total_discountable_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceshipping",
            name="total_taxable_amount",
        ),
    ]
