# Generated by Django 5.2 on 2026-01-08 16:43

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0007_invoice_shipping_amount_invoiceshipping_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="shipping_amount",
            field=djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
        ),
    ]
