# Generated by Django 5.2 on 2026-01-09 09:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("customers", "0002_initial"),
        ("files", "0003_alter_file_purpose"),
        ("invoices", "0008_alter_invoice_shipping_amount"),
        ("numbering_systems", "0002_alter_numberingsystem_applies_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="latest_revision",
        ),
        migrations.CreateModel(
            name="InvoiceHead",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "current",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="invoices.invoice"
                    ),
                ),
                (
                    "root",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="invoices.invoice"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="head",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="invoices.invoicehead",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["head_id"], name="invoices_in_head_id_c9c85f_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["previous_revision_id"], name="invoices_in_previou_6899f3_idx"),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("previous_revision__isnull", False)),
                fields=("previous_revision",),
                name="uniq_single_next_revision",
            ),
        ),
    ]
