# Generated by Django 5.2 on 2026-01-09 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0009_remove_invoice_latest_revision_invoicehead_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="head",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="revisions", to="invoices.invoicehead"
            ),
        ),
    ]
