# Generated by Django 5.2 on 2026-01-17 11:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
        ("invoices", "0010_alter_invoice_head"),
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceCoupon",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="coupons.coupon"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="invoices.invoice"
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="coupons",
            field=models.ManyToManyField(related_name="+", through="invoices.InvoiceCoupon", to="coupons.coupon"),
        ),
        migrations.CreateModel(
            name="InvoiceLineCoupon",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="coupons.coupon"
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="invoices.invoiceline"
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="coupons",
            field=models.ManyToManyField(related_name="+", through="invoices.InvoiceLineCoupon", to="coupons.coupon"),
        ),
        migrations.CreateModel(
            name="InvoiceLineTaxRate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "invoice_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="invoices.invoiceline"
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="taxes.taxrate"
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="tax_rates",
            field=models.ManyToManyField(related_name="+", through="invoices.InvoiceLineTaxRate", to="taxes.taxrate"),
        ),
        migrations.CreateModel(
            name="InvoiceShippingTaxRate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "invoice_shipping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="invoices.invoiceshipping"
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="taxes.taxrate"
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="invoiceshipping",
            name="tax_rates",
            field=models.ManyToManyField(
                related_name="+", through="invoices.InvoiceShippingTaxRate", to="taxes.taxrate"
            ),
        ),
        migrations.CreateModel(
            name="InvoiceTaxRate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="invoices.invoice"
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="taxes.taxrate"
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_rates",
            field=models.ManyToManyField(related_name="+", through="invoices.InvoiceTaxRate", to="taxes.taxrate"),
        ),
        migrations.AddConstraint(
            model_name="invoicecoupon",
            constraint=models.UniqueConstraint(fields=("invoice", "coupon"), name="unique_invoice_coupon_link"),
        ),
        migrations.AddConstraint(
            model_name="invoicecoupon",
            constraint=models.UniqueConstraint(fields=("invoice", "position"), name="unique_invoice_coupon_position"),
        ),
        migrations.AddConstraint(
            model_name="invoicelinecoupon",
            constraint=models.UniqueConstraint(
                fields=("invoice_line", "coupon"), name="unique_invoice_line_coupon_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelinecoupon",
            constraint=models.UniqueConstraint(
                fields=("invoice_line", "position"), name="unique_invoice_line_coupon_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelinetaxrate",
            constraint=models.UniqueConstraint(
                fields=("invoice_line", "tax_rate"), name="unique_invoice_line_tax_rate_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelinetaxrate",
            constraint=models.UniqueConstraint(
                fields=("invoice_line", "position"), name="unique_invoice_line_tax_rate_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceshippingtaxrate",
            constraint=models.UniqueConstraint(
                fields=("invoice_shipping", "tax_rate"), name="unique_invoice_shipping_tax_rate_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceshippingtaxrate",
            constraint=models.UniqueConstraint(
                fields=("invoice_shipping", "position"), name="unique_invoice_shipping_tax_rate_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicetaxrate",
            constraint=models.UniqueConstraint(fields=("invoice", "tax_rate"), name="unique_invoice_tax_rate_link"),
        ),
        migrations.AddConstraint(
            model_name="invoicetaxrate",
            constraint=models.UniqueConstraint(fields=("invoice", "position"), name="unique_invoice_tax_rate_position"),
        ),
    ]
