# Generated by Django 5.2 on 2026-01-17 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0011_invoicecoupon_invoice_coupons_invoicelinecoupon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicecoupon",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invoice_coupons", to="invoices.invoice"
            ),
        ),
        migrations.AlterField(
            model_name="invoicelinecoupon",
            name="invoice_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_line_coupons",
                to="invoices.invoiceline",
            ),
        ),
        migrations.AlterField(
            model_name="invoicelinetaxrate",
            name="invoice_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_line_tax_rates",
                to="invoices.invoiceline",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceshippingtaxrate",
            name="invoice_shipping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_shipping_tax_rates",
                to="invoices.invoiceshipping",
            ),
        ),
        migrations.AlterField(
            model_name="invoicetaxrate",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invoice_tax_rates", to="invoices.invoice"
            ),
        ),
    ]
