# Generated by Django 5.2 on 2026-01-19 10:45

import uuid
from decimal import Decimal

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
        ("invoices", "0012_alter_invoicecoupon_invoice_and_more"),
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicetax",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="invoicetax",
            name="invoice_line",
        ),
        migrations.RemoveField(
            model_name="invoicetax",
            name="invoice_shipping",
        ),
        migrations.RemoveField(
            model_name="invoicetax",
            name="tax_rate",
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="total_taxable_amount",
            field=djmoney.models.fields.MoneyField(
                currency_field_name="currency", decimal_places=2, default=Decimal("0"), max_digits=19
            ),
        ),
        migrations.CreateModel(
            name="InvoiceDiscountAllocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source", models.CharField(choices=[("invoice", "Invoice"), ("line", "Line")], max_length=20)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="coupons.coupon"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_allocations",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_allocations",
                        to="invoices.invoiceline",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTaxAllocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("invoice", "Invoice"), ("line", "Line"), ("shipping", "Shipping")], max_length=20
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_allocations",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_allocations",
                        to="invoices.invoiceline",
                    ),
                ),
                (
                    "invoice_shipping",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_allocations",
                        to="invoices.invoiceshipping",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="taxes.taxrate"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.DeleteModel(
            name="InvoiceDiscount",
        ),
        migrations.DeleteModel(
            name="InvoiceTax",
        ),
        migrations.AddIndex(
            model_name="invoicediscountallocation",
            index=models.Index(fields=["invoice_id", "source"], name="invoices_in_invoice_013152_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicediscountallocation",
            index=models.Index(fields=["invoice_line_id", "source"], name="invoices_in_invoice_40a5e7_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicediscountallocation",
            index=models.Index(fields=["invoice_id", "coupon_id"], name="invoices_in_invoice_e96a79_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicediscountallocation",
            index=models.Index(fields=["invoice_line_id", "coupon_id"], name="invoices_in_invoice_be6e09_idx"),
        ),
        migrations.AddConstraint(
            model_name="invoicediscountallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="discount_allocation_positive_amount"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicetaxallocation",
            index=models.Index(fields=["invoice_id", "source"], name="invoices_in_invoice_83e685_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicetaxallocation",
            index=models.Index(fields=["invoice_id", "tax_rate_id"], name="invoices_in_invoice_ffd329_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicetaxallocation",
            index=models.Index(fields=["invoice_line_id", "tax_rate_id"], name="invoices_in_invoice_672c55_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicetaxallocation",
            index=models.Index(fields=["invoice_shipping_id", "tax_rate_id"], name="invoices_in_invoice_b704b5_idx"),
        ),
        migrations.AddConstraint(
            model_name="invoicetaxallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("invoice_line__isnull", False), ("invoice_shipping__isnull", True)),
                    models.Q(("invoice_line__isnull", True), ("invoice_shipping__isnull", False)),
                    _connector="OR",
                ),
                name="tax_allocation_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicetaxallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="tax_allocation_positive_amount"
            ),
        ),
    ]
