# Generated by Django 5.2 on 2026-01-19 10:45

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0013_remove_invoicetax_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceline",
            name="total_taxable_amount",
            field=djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
        ),
    ]
