# Generated by Django 5.2 on 2026-01-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
        ("invoices", "0014_alter_invoiceline_total_taxable_amount"),
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicecoupon",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoice_coupons", to="coupons.coupon"
            ),
        ),
        migrations.AlterField(
            model_name="invoicelinecoupon",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoice_line_coupons", to="coupons.coupon"
            ),
        ),
        migrations.AlterField(
            model_name="invoicelinetaxrate",
            name="tax_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoice_line_tax_rates", to="taxes.taxrate"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceshippingtaxrate",
            name="tax_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_shipping_tax_rates",
                to="taxes.taxrate",
            ),
        ),
        migrations.AlterField(
            model_name="invoicetaxrate",
            name="tax_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoice_tax_rates", to="taxes.taxrate"
            ),
        ),
    ]
