# Generated by Django 5.2 on 2026-01-23 00:00

from decimal import Decimal

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0016_invoice_tax_behavior_and_unit_excluding_tax_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="total_amount_excluding_tax",
            new_name="total_excluding_tax_amount",
        ),
        migrations.RenameField(
            model_name="invoiceline",
            old_name="total_amount_excluding_tax",
            new_name="total_excluding_tax_amount",
        ),
        migrations.AddField(
            model_name="invoiceshipping",
            name="total_excluding_tax_amount",
            field=djmoney.models.fields.MoneyField(
                currency_field_name="currency",
                decimal_places=2,
                default=Decimal("0"),
                max_digits=19,
            ),
            preserve_default=False,
        ),
    ]
