# Generated by Django 5.2 on 2026-01-23 00:00

from decimal import Decimal

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0017_rename_total_excluding_tax_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceshipping",
            name="total_taxable_amount",
            field=djmoney.models.fields.MoneyField(
                currency_field_name="currency",
                decimal_places=2,
                default=Decimal("0"),
                max_digits=19,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceshipping",
            name="total_tax_rate",
            field=models.DecimalField(max_digits=5, decimal_places=2, default=Decimal("0")),
            preserve_default=False,
        ),
    ]
