/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type {
  GetGrossRevenueParams,
  GetOverdueBalanceParams,
  GrossRevenue,
  OverdueBalance,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getGrossRevenue = (
  params?: GetGrossRevenueParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<GrossRevenue[]>(
    { url: `/api/v1/analytics/gross-revenue`, method: "GET", params, signal },
    options,
  );
};

export const getGetGrossRevenueQueryKey = (params?: GetGrossRevenueParams) => {
  return [
    `/api/v1/analytics/gross-revenue`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGrossRevenueQueryOptions = <
  TData = Awaited<ReturnType<typeof getGrossRevenue>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGrossRevenueParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGrossRevenue>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGrossRevenueQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGrossRevenue>>> = ({
    signal,
  }) => getGrossRevenue(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGrossRevenue>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGrossRevenueQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGrossRevenue>>
>;
export type GetGrossRevenueQueryError = ErrorType<unknown>;

export function useGetGrossRevenue<
  TData = Awaited<ReturnType<typeof getGrossRevenue>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGrossRevenueParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGrossRevenue>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGrossRevenue>>,
          TError,
          Awaited<ReturnType<typeof getGrossRevenue>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGrossRevenue<
  TData = Awaited<ReturnType<typeof getGrossRevenue>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGrossRevenueParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGrossRevenue>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGrossRevenue>>,
          TError,
          Awaited<ReturnType<typeof getGrossRevenue>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGrossRevenue<
  TData = Awaited<ReturnType<typeof getGrossRevenue>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGrossRevenueParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGrossRevenue>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGrossRevenue<
  TData = Awaited<ReturnType<typeof getGrossRevenue>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGrossRevenueParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGrossRevenue>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGrossRevenueQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetGrossRevenueSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getGrossRevenue>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGrossRevenueParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getGrossRevenue>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGrossRevenueQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGrossRevenue>>> = ({
    signal,
  }) => getGrossRevenue(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getGrossRevenue>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGrossRevenueSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGrossRevenue>>
>;
export type GetGrossRevenueSuspenseQueryError = ErrorType<unknown>;

export function useGetGrossRevenueSuspense<
  TData = Awaited<ReturnType<typeof getGrossRevenue>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGrossRevenueParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getGrossRevenue>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGrossRevenueSuspense<
  TData = Awaited<ReturnType<typeof getGrossRevenue>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGrossRevenueParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getGrossRevenue>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGrossRevenueSuspense<
  TData = Awaited<ReturnType<typeof getGrossRevenue>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGrossRevenueParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getGrossRevenue>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGrossRevenueSuspense<
  TData = Awaited<ReturnType<typeof getGrossRevenue>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGrossRevenueParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getGrossRevenue>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGrossRevenueSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getOverdueBalance = (
  params?: GetOverdueBalanceParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<OverdueBalance[]>(
    { url: `/api/v1/analytics/overdue-balance`, method: "GET", params, signal },
    options,
  );
};

export const getGetOverdueBalanceQueryKey = (
  params?: GetOverdueBalanceParams,
) => {
  return [
    `/api/v1/analytics/overdue-balance`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetOverdueBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverdueBalance>>,
  TError = ErrorType<unknown>,
>(
  params?: GetOverdueBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverdueBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOverdueBalanceQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverdueBalance>>
  > = ({ signal }) => getOverdueBalance(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverdueBalance>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOverdueBalanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverdueBalance>>
>;
export type GetOverdueBalanceQueryError = ErrorType<unknown>;

export function useGetOverdueBalance<
  TData = Awaited<ReturnType<typeof getOverdueBalance>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetOverdueBalanceParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverdueBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverdueBalance>>,
          TError,
          Awaited<ReturnType<typeof getOverdueBalance>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverdueBalance<
  TData = Awaited<ReturnType<typeof getOverdueBalance>>,
  TError = ErrorType<unknown>,
>(
  params?: GetOverdueBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverdueBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverdueBalance>>,
          TError,
          Awaited<ReturnType<typeof getOverdueBalance>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverdueBalance<
  TData = Awaited<ReturnType<typeof getOverdueBalance>>,
  TError = ErrorType<unknown>,
>(
  params?: GetOverdueBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverdueBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetOverdueBalance<
  TData = Awaited<ReturnType<typeof getOverdueBalance>>,
  TError = ErrorType<unknown>,
>(
  params?: GetOverdueBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverdueBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOverdueBalanceQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetOverdueBalanceSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverdueBalance>>,
  TError = ErrorType<unknown>,
>(
  params?: GetOverdueBalanceParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getOverdueBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOverdueBalanceQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverdueBalance>>
  > = ({ signal }) => getOverdueBalance(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getOverdueBalance>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOverdueBalanceSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverdueBalance>>
>;
export type GetOverdueBalanceSuspenseQueryError = ErrorType<unknown>;

export function useGetOverdueBalanceSuspense<
  TData = Awaited<ReturnType<typeof getOverdueBalance>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetOverdueBalanceParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getOverdueBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverdueBalanceSuspense<
  TData = Awaited<ReturnType<typeof getOverdueBalance>>,
  TError = ErrorType<unknown>,
>(
  params?: GetOverdueBalanceParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getOverdueBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverdueBalanceSuspense<
  TData = Awaited<ReturnType<typeof getOverdueBalance>>,
  TError = ErrorType<unknown>,
>(
  params?: GetOverdueBalanceParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getOverdueBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetOverdueBalanceSuspense<
  TData = Awaited<ReturnType<typeof getOverdueBalance>>,
  TError = ErrorType<unknown>,
>(
  params?: GetOverdueBalanceParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getOverdueBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOverdueBalanceSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
