# Generated by Django 5.2 on 2026-01-23 18:03

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNoteLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.BigIntegerField(null=True)),
                ("currency", models.CharField(max_length=3)),
                (
                    "unit_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount_excluding_tax",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditNoteTax",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255, null=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=255, null=True)),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("issued", "Issued"), ("voided", "Voided")], max_length=50
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("duplicated_charge", "Duplicated Charge"),
                            ("product_unsatisfactory", "Product Unsatisfactory"),
                            ("order_change", "Order Change"),
                            ("order_cancellation", "Order Cancellation"),
                            ("fraudulent_charge", "Fraudulent Charge"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("issue_date", models.DateField(null=True)),
                ("description", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "subtotal_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount_excluding_tax",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("payment_provider", models.CharField(choices=[("stripe", "Stripe")], max_length=50, null=True)),
                ("payment_connection_id", models.UUIDField(null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")], default="manual", max_length=20
                    ),
                ),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254), blank=True, default=list, size=None
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("issued_at", models.DateTimeField(null=True)),
                ("voided_at", models.DateTimeField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="credit_notes", to="accounts.account"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
