# Generated by Django 5.2 on 2025-10-27 20:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("files", "0001_initial"),
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(null=True)),
                ("is_active", models.BooleanField()),
                ("metadata", models.JSONField(default=dict)),
                ("archived_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="accounts.account"
                    ),
                ),
                (
                    "default_price",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_product",
                        to="prices.price",
                    ),
                ),
                ("image", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="files.file")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
