# Generated by Django 5.2 on 2026-02-05 17:42

import uuid

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("api_key", encrypted_fields.fields.EncryptedTextField()),
                ("webhook_endpoint_id", models.CharField(max_length=255)),
                ("webhook_secret", encrypted_fields.fields.EncryptedTextField()),
                ("redirect_url", models.URLField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_connections",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
