# Generated by Django 5.2 on 2026-01-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0004_remove_price_is_used_alter_price_product"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="default_price",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_product",
                to="prices.price",
            ),
        ),
    ]
