# Generated by Django 5.2 on 2026-01-23 18:03

import uuid

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("description", models.CharField(max_length=255, null=True)),
                ("transaction_id", models.CharField(max_length=255, null=True)),
                ("url", models.URLField(null=True)),
                ("message", models.TextField(null=True)),
                ("extra_data", models.JSONField(default=dict)),
                ("provider", models.CharField(choices=[("stripe", "Stripe")], max_length=50, null=True)),
                ("connection_id", models.UUIDField(null=True)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="accounts.account"
                    ),
                ),
                ("invoices", models.ManyToManyField(related_name="payments", to="invoices.invoice")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
