# Generated by Django 5.2 on 2025-12-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="connection_id",
            field=models.UUIDField(null=True),
        ),
    ]
