# Generated by Django 5.2 on 2026-02-05 17:42

import uuid

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("line1", models.CharField(max_length=255, null=True)),
                ("line2", models.CharField(max_length=255, null=True)),
                ("locality", models.CharField(max_length=255, null=True)),
                ("state", models.CharField(max_length=255, null=True)),
                ("postal_code", models.CharField(max_length=255, null=True)),
                ("country", django_countries.fields.CountryField(max_length=2, null=True)),
            ],
        ),
    ]
