# Generated by Django 5.2 on 2026-01-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_alter_customer_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="net_payment_term",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
