# Generated by Django 5.2 on 2026-02-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("credit_notes", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="credit_notes", to="customers.customer"
            ),
        ),
    ]
