# Generated by Django 5.2 on 2026-01-29 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credit_notes", "0005_alter_creditnote_numbering_system_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditnote",
            name="description",
        ),
    ]
