# Generated by Django 5.2 on 2026-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_notes", "0005_alter_creditnote_numbering_system_and_more"),
        ("notes", "__first__"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditnote",
            name="description",
        ),
        migrations.AddField(
            model_name="creditnote",
            name="notes",
            field=models.ManyToManyField(related_name="credit_notes", to="notes.note"),
        ),
    ]
