# Generated by Django 5.2 on 2026-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
        ("credit_notes", "0006_remove_creditnote_description_creditnote_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="comments",
            field=models.ManyToManyField(related_name="credit_notes", to="comments.comment"),
        ),
    ]
