/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type {
  InvoiceLine,
  InvoiceLineCreate,
  InvoiceLineUpdate,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const createInvoiceLine = (
  invoiceLineCreate: InvoiceLineCreate,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<InvoiceLine>(
    {
      url: `/api/v1/invoice-lines`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: invoiceLineCreate,
      signal,
    },
    options,
  );
};

export const getCreateInvoiceLineMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createInvoiceLine>>,
    TError,
    { data: InvoiceLineCreate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createInvoiceLine>>,
  TError,
  { data: InvoiceLineCreate },
  TContext
> => {
  const mutationKey = ["createInvoiceLine"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createInvoiceLine>>,
    { data: InvoiceLineCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createInvoiceLine(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateInvoiceLineMutationResult = NonNullable<
  Awaited<ReturnType<typeof createInvoiceLine>>
>;
export type CreateInvoiceLineMutationBody = InvoiceLineCreate;
export type CreateInvoiceLineMutationError = ErrorType<unknown>;

export const useCreateInvoiceLine = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createInvoiceLine>>,
      TError,
      { data: InvoiceLineCreate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createInvoiceLine>>,
  TError,
  { data: InvoiceLineCreate },
  TContext
> => {
  const mutationOptions = getCreateInvoiceLineMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const updateInvoiceLine = (
  id: string,
  invoiceLineUpdate: InvoiceLineUpdate,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<InvoiceLine>(
    {
      url: `/api/v1/invoice-lines/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: invoiceLineUpdate,
    },
    options,
  );
};

export const getUpdateInvoiceLineMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateInvoiceLine>>,
    TError,
    { id: string; data: InvoiceLineUpdate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateInvoiceLine>>,
  TError,
  { id: string; data: InvoiceLineUpdate },
  TContext
> => {
  const mutationKey = ["updateInvoiceLine"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateInvoiceLine>>,
    { id: string; data: InvoiceLineUpdate }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateInvoiceLine(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateInvoiceLineMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateInvoiceLine>>
>;
export type UpdateInvoiceLineMutationBody = InvoiceLineUpdate;
export type UpdateInvoiceLineMutationError = ErrorType<unknown>;

export const useUpdateInvoiceLine = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateInvoiceLine>>,
      TError,
      { id: string; data: InvoiceLineUpdate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateInvoiceLine>>,
  TError,
  { id: string; data: InvoiceLineUpdate },
  TContext
> => {
  const mutationOptions = getUpdateInvoiceLineMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteInvoiceLine = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<void>(
    { url: `/api/v1/invoice-lines/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteInvoiceLineMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteInvoiceLine>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteInvoiceLine>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteInvoiceLine"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteInvoiceLine>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteInvoiceLine(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteInvoiceLineMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteInvoiceLine>>
>;

export type DeleteInvoiceLineMutationError = ErrorType<unknown>;

export const useDeleteInvoiceLine = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteInvoiceLine>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteInvoiceLine>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteInvoiceLineMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
