/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type {
  InvoiceLine,
  InvoiceLineCreate,
  InvoiceLineDiscount,
  InvoiceLineDiscountCreate,
  InvoiceLineTax,
  InvoiceLineTaxCreate,
  InvoiceLineUpdate,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const createInvoiceLine = (
  invoiceLineCreate: InvoiceLineCreate,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<InvoiceLine>(
    {
      url: `/api/v1/invoice-lines`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: invoiceLineCreate,
      signal,
    },
    options,
  );
};

export const getCreateInvoiceLineMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createInvoiceLine>>,
    TError,
    { data: InvoiceLineCreate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createInvoiceLine>>,
  TError,
  { data: InvoiceLineCreate },
  TContext
> => {
  const mutationKey = ["createInvoiceLine"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createInvoiceLine>>,
    { data: InvoiceLineCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createInvoiceLine(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateInvoiceLineMutationResult = NonNullable<
  Awaited<ReturnType<typeof createInvoiceLine>>
>;
export type CreateInvoiceLineMutationBody = InvoiceLineCreate;
export type CreateInvoiceLineMutationError = ErrorType<unknown>;

export const useCreateInvoiceLine = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createInvoiceLine>>,
      TError,
      { data: InvoiceLineCreate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createInvoiceLine>>,
  TError,
  { data: InvoiceLineCreate },
  TContext
> => {
  const mutationOptions = getCreateInvoiceLineMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteInvoiceLineDiscount = (
  invoiceLineId: string,
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<void>(
    {
      url: `/api/v1/invoice-lines/${invoiceLineId}/discounts/${id}`,
      method: "DELETE",
    },
    options,
  );
};

export const getDeleteInvoiceLineDiscountMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteInvoiceLineDiscount>>,
    TError,
    { invoiceLineId: string; id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteInvoiceLineDiscount>>,
  TError,
  { invoiceLineId: string; id: string },
  TContext
> => {
  const mutationKey = ["deleteInvoiceLineDiscount"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteInvoiceLineDiscount>>,
    { invoiceLineId: string; id: string }
  > = (props) => {
    const { invoiceLineId, id } = props ?? {};

    return deleteInvoiceLineDiscount(invoiceLineId, id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteInvoiceLineDiscountMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteInvoiceLineDiscount>>
>;

export type DeleteInvoiceLineDiscountMutationError = ErrorType<unknown>;

export const useDeleteInvoiceLineDiscount = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteInvoiceLineDiscount>>,
      TError,
      { invoiceLineId: string; id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteInvoiceLineDiscount>>,
  TError,
  { invoiceLineId: string; id: string },
  TContext
> => {
  const mutationOptions = getDeleteInvoiceLineDiscountMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteInvoiceLineTax = (
  invoiceLineId: string,
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<void>(
    {
      url: `/api/v1/invoice-lines/${invoiceLineId}/taxes/${id}`,
      method: "DELETE",
    },
    options,
  );
};

export const getDeleteInvoiceLineTaxMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteInvoiceLineTax>>,
    TError,
    { invoiceLineId: string; id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteInvoiceLineTax>>,
  TError,
  { invoiceLineId: string; id: string },
  TContext
> => {
  const mutationKey = ["deleteInvoiceLineTax"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteInvoiceLineTax>>,
    { invoiceLineId: string; id: string }
  > = (props) => {
    const { invoiceLineId, id } = props ?? {};

    return deleteInvoiceLineTax(invoiceLineId, id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteInvoiceLineTaxMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteInvoiceLineTax>>
>;

export type DeleteInvoiceLineTaxMutationError = ErrorType<unknown>;

export const useDeleteInvoiceLineTax = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteInvoiceLineTax>>,
      TError,
      { invoiceLineId: string; id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteInvoiceLineTax>>,
  TError,
  { invoiceLineId: string; id: string },
  TContext
> => {
  const mutationOptions = getDeleteInvoiceLineTaxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const updateInvoiceLine = (
  id: string,
  invoiceLineUpdate: InvoiceLineUpdate,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<InvoiceLine>(
    {
      url: `/api/v1/invoice-lines/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: invoiceLineUpdate,
    },
    options,
  );
};

export const getUpdateInvoiceLineMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateInvoiceLine>>,
    TError,
    { id: string; data: InvoiceLineUpdate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateInvoiceLine>>,
  TError,
  { id: string; data: InvoiceLineUpdate },
  TContext
> => {
  const mutationKey = ["updateInvoiceLine"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateInvoiceLine>>,
    { id: string; data: InvoiceLineUpdate }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateInvoiceLine(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateInvoiceLineMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateInvoiceLine>>
>;
export type UpdateInvoiceLineMutationBody = InvoiceLineUpdate;
export type UpdateInvoiceLineMutationError = ErrorType<unknown>;

export const useUpdateInvoiceLine = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateInvoiceLine>>,
      TError,
      { id: string; data: InvoiceLineUpdate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateInvoiceLine>>,
  TError,
  { id: string; data: InvoiceLineUpdate },
  TContext
> => {
  const mutationOptions = getUpdateInvoiceLineMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteInvoiceLine = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<void>(
    { url: `/api/v1/invoice-lines/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteInvoiceLineMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteInvoiceLine>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteInvoiceLine>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteInvoiceLine"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteInvoiceLine>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteInvoiceLine(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteInvoiceLineMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteInvoiceLine>>
>;

export type DeleteInvoiceLineMutationError = ErrorType<unknown>;

export const useDeleteInvoiceLine = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteInvoiceLine>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteInvoiceLine>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteInvoiceLineMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const applyInvoiceLineDiscount = (
  id: string,
  invoiceLineDiscountCreate: InvoiceLineDiscountCreate,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<InvoiceLineDiscount>(
    {
      url: `/api/v1/invoice-lines/${id}/discounts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: invoiceLineDiscountCreate,
      signal,
    },
    options,
  );
};

export const getApplyInvoiceLineDiscountMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof applyInvoiceLineDiscount>>,
    TError,
    { id: string; data: InvoiceLineDiscountCreate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof applyInvoiceLineDiscount>>,
  TError,
  { id: string; data: InvoiceLineDiscountCreate },
  TContext
> => {
  const mutationKey = ["applyInvoiceLineDiscount"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof applyInvoiceLineDiscount>>,
    { id: string; data: InvoiceLineDiscountCreate }
  > = (props) => {
    const { id, data } = props ?? {};

    return applyInvoiceLineDiscount(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApplyInvoiceLineDiscountMutationResult = NonNullable<
  Awaited<ReturnType<typeof applyInvoiceLineDiscount>>
>;
export type ApplyInvoiceLineDiscountMutationBody = InvoiceLineDiscountCreate;
export type ApplyInvoiceLineDiscountMutationError = ErrorType<unknown>;

export const useApplyInvoiceLineDiscount = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof applyInvoiceLineDiscount>>,
      TError,
      { id: string; data: InvoiceLineDiscountCreate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof applyInvoiceLineDiscount>>,
  TError,
  { id: string; data: InvoiceLineDiscountCreate },
  TContext
> => {
  const mutationOptions = getApplyInvoiceLineDiscountMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const applyInvoiceLineTax = (
  id: string,
  invoiceLineTaxCreate: InvoiceLineTaxCreate,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<InvoiceLineTax>(
    {
      url: `/api/v1/invoice-lines/${id}/taxes`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: invoiceLineTaxCreate,
      signal,
    },
    options,
  );
};

export const getApplyInvoiceLineTaxMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof applyInvoiceLineTax>>,
    TError,
    { id: string; data: InvoiceLineTaxCreate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof applyInvoiceLineTax>>,
  TError,
  { id: string; data: InvoiceLineTaxCreate },
  TContext
> => {
  const mutationKey = ["applyInvoiceLineTax"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof applyInvoiceLineTax>>,
    { id: string; data: InvoiceLineTaxCreate }
  > = (props) => {
    const { id, data } = props ?? {};

    return applyInvoiceLineTax(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApplyInvoiceLineTaxMutationResult = NonNullable<
  Awaited<ReturnType<typeof applyInvoiceLineTax>>
>;
export type ApplyInvoiceLineTaxMutationBody = InvoiceLineTaxCreate;
export type ApplyInvoiceLineTaxMutationError = ErrorType<unknown>;

export const useApplyInvoiceLineTax = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof applyInvoiceLineTax>>,
      TError,
      { id: string; data: InvoiceLineTaxCreate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof applyInvoiceLineTax>>,
  TError,
  { id: string; data: InvoiceLineTaxCreate },
  TContext
> => {
  const mutationOptions = getApplyInvoiceLineTaxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
