# Generated by Django 5.2 on 2025-10-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stripe_customer",
                        serialize=False,
                        to="accounts.account",
                    ),
                ),
                ("customer_id", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="StripeSubscription",
            fields=[
                ("subscription_id", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("price_id", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "stripe_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="stripe.stripecustomer",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["stripe_customer", "status"], name="stripe_stri_stripe__d70f79_idx")],
            },
        ),
    ]
