/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type {
  PaginatedTaxRateList,
  TaxRate,
  TaxRateCreate,
  TaxRatesListParams,
  TaxRateUpdate,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const taxRatesList = (
  params?: TaxRatesListParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedTaxRateList>(
    { url: `/api/v1/tax-rates`, method: "GET", params, signal },
    options,
  );
};

export const getTaxRatesListQueryKey = (params?: TaxRatesListParams) => {
  return [`/api/v1/tax-rates`, ...(params ? [params] : [])] as const;
};

export const getTaxRatesListQueryOptions = <
  TData = Awaited<ReturnType<typeof taxRatesList>>,
  TError = ErrorType<unknown>,
>(
  params?: TaxRatesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof taxRatesList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTaxRatesListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof taxRatesList>>> = ({
    signal,
  }) => taxRatesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof taxRatesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TaxRatesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof taxRatesList>>
>;
export type TaxRatesListQueryError = ErrorType<unknown>;

export function useTaxRatesList<
  TData = Awaited<ReturnType<typeof taxRatesList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | TaxRatesListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof taxRatesList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof taxRatesList>>,
          TError,
          Awaited<ReturnType<typeof taxRatesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTaxRatesList<
  TData = Awaited<ReturnType<typeof taxRatesList>>,
  TError = ErrorType<unknown>,
>(
  params?: TaxRatesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof taxRatesList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof taxRatesList>>,
          TError,
          Awaited<ReturnType<typeof taxRatesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTaxRatesList<
  TData = Awaited<ReturnType<typeof taxRatesList>>,
  TError = ErrorType<unknown>,
>(
  params?: TaxRatesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof taxRatesList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useTaxRatesList<
  TData = Awaited<ReturnType<typeof taxRatesList>>,
  TError = ErrorType<unknown>,
>(
  params?: TaxRatesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof taxRatesList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTaxRatesListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getTaxRatesListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof taxRatesList>>,
  TError = ErrorType<unknown>,
>(
  params?: TaxRatesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof taxRatesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTaxRatesListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof taxRatesList>>> = ({
    signal,
  }) => taxRatesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof taxRatesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TaxRatesListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof taxRatesList>>
>;
export type TaxRatesListSuspenseQueryError = ErrorType<unknown>;

export function useTaxRatesListSuspense<
  TData = Awaited<ReturnType<typeof taxRatesList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | TaxRatesListParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof taxRatesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTaxRatesListSuspense<
  TData = Awaited<ReturnType<typeof taxRatesList>>,
  TError = ErrorType<unknown>,
>(
  params?: TaxRatesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof taxRatesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTaxRatesListSuspense<
  TData = Awaited<ReturnType<typeof taxRatesList>>,
  TError = ErrorType<unknown>,
>(
  params?: TaxRatesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof taxRatesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useTaxRatesListSuspense<
  TData = Awaited<ReturnType<typeof taxRatesList>>,
  TError = ErrorType<unknown>,
>(
  params?: TaxRatesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof taxRatesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTaxRatesListSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createTaxRate = (
  taxRateCreate: TaxRateCreate,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<TaxRate>(
    {
      url: `/api/v1/tax-rates`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: taxRateCreate,
      signal,
    },
    options,
  );
};

export const getCreateTaxRateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTaxRate>>,
    TError,
    { data: TaxRateCreate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTaxRate>>,
  TError,
  { data: TaxRateCreate },
  TContext
> => {
  const mutationKey = ["createTaxRate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTaxRate>>,
    { data: TaxRateCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createTaxRate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTaxRateMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTaxRate>>
>;
export type CreateTaxRateMutationBody = TaxRateCreate;
export type CreateTaxRateMutationError = ErrorType<unknown>;

export const useCreateTaxRate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createTaxRate>>,
      TError,
      { data: TaxRateCreate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createTaxRate>>,
  TError,
  { data: TaxRateCreate },
  TContext
> => {
  const mutationOptions = getCreateTaxRateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const taxRatesRetrieve = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<TaxRate>(
    { url: `/api/v1/tax-rates/${id}`, method: "GET", signal },
    options,
  );
};

export const getTaxRatesRetrieveQueryKey = (id?: string) => {
  return [`/api/v1/tax-rates/${id}`] as const;
};

export const getTaxRatesRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof taxRatesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof taxRatesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTaxRatesRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof taxRatesRetrieve>>
  > = ({ signal }) => taxRatesRetrieve(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof taxRatesRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TaxRatesRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof taxRatesRetrieve>>
>;
export type TaxRatesRetrieveQueryError = ErrorType<unknown>;

export function useTaxRatesRetrieve<
  TData = Awaited<ReturnType<typeof taxRatesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof taxRatesRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof taxRatesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof taxRatesRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTaxRatesRetrieve<
  TData = Awaited<ReturnType<typeof taxRatesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof taxRatesRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof taxRatesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof taxRatesRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTaxRatesRetrieve<
  TData = Awaited<ReturnType<typeof taxRatesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof taxRatesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useTaxRatesRetrieve<
  TData = Awaited<ReturnType<typeof taxRatesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof taxRatesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTaxRatesRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getTaxRatesRetrieveSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof taxRatesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof taxRatesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTaxRatesRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof taxRatesRetrieve>>
  > = ({ signal }) => taxRatesRetrieve(id, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof taxRatesRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TaxRatesRetrieveSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof taxRatesRetrieve>>
>;
export type TaxRatesRetrieveSuspenseQueryError = ErrorType<unknown>;

export function useTaxRatesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof taxRatesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof taxRatesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTaxRatesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof taxRatesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof taxRatesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTaxRatesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof taxRatesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof taxRatesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useTaxRatesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof taxRatesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof taxRatesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTaxRatesRetrieveSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateTaxRate = (
  id: string,
  taxRateUpdate: TaxRateUpdate,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<TaxRate>(
    {
      url: `/api/v1/tax-rates/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: taxRateUpdate,
    },
    options,
  );
};

export const getUpdateTaxRateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTaxRate>>,
    TError,
    { id: string; data: TaxRateUpdate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTaxRate>>,
  TError,
  { id: string; data: TaxRateUpdate },
  TContext
> => {
  const mutationKey = ["updateTaxRate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTaxRate>>,
    { id: string; data: TaxRateUpdate }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateTaxRate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTaxRateMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateTaxRate>>
>;
export type UpdateTaxRateMutationBody = TaxRateUpdate;
export type UpdateTaxRateMutationError = ErrorType<unknown>;

export const useUpdateTaxRate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateTaxRate>>,
      TError,
      { id: string; data: TaxRateUpdate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateTaxRate>>,
  TError,
  { id: string; data: TaxRateUpdate },
  TContext
> => {
  const mutationOptions = getUpdateTaxRateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const archiveTaxRate = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<TaxRate>(
    { url: `/api/v1/tax-rates/${id}/archive`, method: "POST", signal },
    options,
  );
};

export const getArchiveTaxRateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof archiveTaxRate>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof archiveTaxRate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["archiveTaxRate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof archiveTaxRate>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return archiveTaxRate(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ArchiveTaxRateMutationResult = NonNullable<
  Awaited<ReturnType<typeof archiveTaxRate>>
>;

export type ArchiveTaxRateMutationError = ErrorType<unknown>;

export const useArchiveTaxRate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof archiveTaxRate>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof archiveTaxRate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getArchiveTaxRateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const unarchiveTaxRate = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<TaxRate>(
    { url: `/api/v1/tax-rates/${id}/unarchive`, method: "POST", signal },
    options,
  );
};

export const getUnarchiveTaxRateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unarchiveTaxRate>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unarchiveTaxRate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["unarchiveTaxRate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unarchiveTaxRate>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return unarchiveTaxRate(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnarchiveTaxRateMutationResult = NonNullable<
  Awaited<ReturnType<typeof unarchiveTaxRate>>
>;

export type UnarchiveTaxRateMutationError = ErrorType<unknown>;

export const useUnarchiveTaxRate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unarchiveTaxRate>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof unarchiveTaxRate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getUnarchiveTaxRateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
