# Generated by Django 5.2 on 2026-01-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numbering_systems", "0001_initial"),
        ("quotes", "0003_quote_customer_address"),
        ("tax_rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="numbering_system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="numbering_systems.numberingsystem",
            ),
        ),
        migrations.AlterField(
            model_name="quotetax",
            name="tax_rate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quote_taxes",
                to="tax_rates.taxrate",
            ),
        ),
    ]
