/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type {
  BillingProfile,
  BillingProfileCreate,
  BillingProfilesListParams,
  BillingProfileUpdate,
  PaginatedBillingProfileList,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const billingProfilesList = (
  params?: BillingProfilesListParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedBillingProfileList>(
    { url: `/api/v1/billing-profiles`, method: "GET", params, signal },
    options,
  );
};

export const getBillingProfilesListQueryKey = (
  params?: BillingProfilesListParams,
) => {
  return [`/api/v1/billing-profiles`, ...(params ? [params] : [])] as const;
};

export const getBillingProfilesListQueryOptions = <
  TData = Awaited<ReturnType<typeof billingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BillingProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBillingProfilesListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof billingProfilesList>>
  > = ({ signal }) => billingProfilesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof billingProfilesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BillingProfilesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof billingProfilesList>>
>;
export type BillingProfilesListQueryError = ErrorType<unknown>;

export function useBillingProfilesList<
  TData = Awaited<ReturnType<typeof billingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | BillingProfilesListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof billingProfilesList>>,
          TError,
          Awaited<ReturnType<typeof billingProfilesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBillingProfilesList<
  TData = Awaited<ReturnType<typeof billingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BillingProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof billingProfilesList>>,
          TError,
          Awaited<ReturnType<typeof billingProfilesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBillingProfilesList<
  TData = Awaited<ReturnType<typeof billingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BillingProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useBillingProfilesList<
  TData = Awaited<ReturnType<typeof billingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BillingProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBillingProfilesListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getBillingProfilesListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof billingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BillingProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBillingProfilesListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof billingProfilesList>>
  > = ({ signal }) => billingProfilesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof billingProfilesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BillingProfilesListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof billingProfilesList>>
>;
export type BillingProfilesListSuspenseQueryError = ErrorType<unknown>;

export function useBillingProfilesListSuspense<
  TData = Awaited<ReturnType<typeof billingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | BillingProfilesListParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBillingProfilesListSuspense<
  TData = Awaited<ReturnType<typeof billingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BillingProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBillingProfilesListSuspense<
  TData = Awaited<ReturnType<typeof billingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BillingProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useBillingProfilesListSuspense<
  TData = Awaited<ReturnType<typeof billingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BillingProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBillingProfilesListSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createBillingProfile = (
  billingProfileCreate: BillingProfileCreate,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<BillingProfile>(
    {
      url: `/api/v1/billing-profiles`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: billingProfileCreate,
      signal,
    },
    options,
  );
};

export const getCreateBillingProfileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBillingProfile>>,
    TError,
    { data: BillingProfileCreate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createBillingProfile>>,
  TError,
  { data: BillingProfileCreate },
  TContext
> => {
  const mutationKey = ["createBillingProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createBillingProfile>>,
    { data: BillingProfileCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createBillingProfile(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateBillingProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof createBillingProfile>>
>;
export type CreateBillingProfileMutationBody = BillingProfileCreate;
export type CreateBillingProfileMutationError = ErrorType<unknown>;

export const useCreateBillingProfile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createBillingProfile>>,
      TError,
      { data: BillingProfileCreate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createBillingProfile>>,
  TError,
  { data: BillingProfileCreate },
  TContext
> => {
  const mutationOptions = getCreateBillingProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const billingProfilesRetrieve = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<BillingProfile>(
    { url: `/api/v1/billing-profiles/${id}`, method: "GET", signal },
    options,
  );
};

export const getBillingProfilesRetrieveQueryKey = (id?: string) => {
  return [`/api/v1/billing-profiles/${id}`] as const;
};

export const getBillingProfilesRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof billingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBillingProfilesRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof billingProfilesRetrieve>>
  > = ({ signal }) => billingProfilesRetrieve(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof billingProfilesRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BillingProfilesRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof billingProfilesRetrieve>>
>;
export type BillingProfilesRetrieveQueryError = ErrorType<unknown>;

export function useBillingProfilesRetrieve<
  TData = Awaited<ReturnType<typeof billingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof billingProfilesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof billingProfilesRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBillingProfilesRetrieve<
  TData = Awaited<ReturnType<typeof billingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof billingProfilesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof billingProfilesRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBillingProfilesRetrieve<
  TData = Awaited<ReturnType<typeof billingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useBillingProfilesRetrieve<
  TData = Awaited<ReturnType<typeof billingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBillingProfilesRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getBillingProfilesRetrieveSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof billingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBillingProfilesRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof billingProfilesRetrieve>>
  > = ({ signal }) => billingProfilesRetrieve(id, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof billingProfilesRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BillingProfilesRetrieveSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof billingProfilesRetrieve>>
>;
export type BillingProfilesRetrieveSuspenseQueryError = ErrorType<unknown>;

export function useBillingProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof billingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBillingProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof billingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBillingProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof billingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useBillingProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof billingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof billingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBillingProfilesRetrieveSuspenseQueryOptions(
    id,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateBillingProfile = (
  id: string,
  billingProfileUpdate: BillingProfileUpdate,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<BillingProfile>(
    {
      url: `/api/v1/billing-profiles/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: billingProfileUpdate,
    },
    options,
  );
};

export const getUpdateBillingProfileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateBillingProfile>>,
    TError,
    { id: string; data: BillingProfileUpdate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateBillingProfile>>,
  TError,
  { id: string; data: BillingProfileUpdate },
  TContext
> => {
  const mutationKey = ["updateBillingProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateBillingProfile>>,
    { id: string; data: BillingProfileUpdate }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateBillingProfile(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateBillingProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateBillingProfile>>
>;
export type UpdateBillingProfileMutationBody = BillingProfileUpdate;
export type UpdateBillingProfileMutationError = ErrorType<unknown>;

export const useUpdateBillingProfile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateBillingProfile>>,
      TError,
      { id: string; data: BillingProfileUpdate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateBillingProfile>>,
  TError,
  { id: string; data: BillingProfileUpdate },
  TContext
> => {
  const mutationOptions = getUpdateBillingProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteBillingProfile = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<void>(
    { url: `/api/v1/billing-profiles/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteBillingProfileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteBillingProfile>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteBillingProfile>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteBillingProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteBillingProfile>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteBillingProfile(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteBillingProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteBillingProfile>>
>;

export type DeleteBillingProfileMutationError = ErrorType<unknown>;

export const useDeleteBillingProfile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteBillingProfile>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteBillingProfile>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteBillingProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
