# Generated by Django 5.2 on 2026-02-05 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("addresses", "0001_initial"),
        ("files", "0001_initial"),
        ("numbering_systems", "0001_initial"),
        ("tax_ids", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="account",
            name="credit_note_numbering_system",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_note_numbering_account",
                to="numbering_systems.numberingsystem",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="invoice_numbering_system",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_numbering_account",
                to="numbering_systems.numberingsystem",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="logo",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="account_logo", to="files.file"
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_profile_address",
                to="addresses.address",
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="tax_ids",
            field=models.ManyToManyField(related_name="business_profiles", to="tax_ids.taxid"),
        ),
        migrations.AddField(
            model_name="account",
            name="business_profiles",
            field=models.ManyToManyField(related_name="accounts", to="accounts.businessprofile"),
        ),
        migrations.AddField(
            model_name="account",
            name="default_business_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="accounts.businessprofile"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="accounts.account"
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="invited_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="member",
            name="account",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.account"),
        ),
        migrations.AddField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="member", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="members",
            field=models.ManyToManyField(
                related_name="accounts_member_of", through="accounts.Member", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("user", "account")},
        ),
    ]
