# Generated by Django 5.2 on 2026-02-06 00:00

from django.db import migrations, models


def set_account_details(apps, _schema_editor):
    Account = apps.get_model("accounts", "Account")
    for account in Account.objects.select_related("default_business_profile", "created_by"):
        business_profile = account.default_business_profile
        account.name = business_profile.name if business_profile else ""
        account.email = business_profile.email or account.created_by.email
        account.save(update_fields=["name", "email"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.RunPython(set_account_details, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="name",
        ),
    ]
