# Generated by Django 5.2 on 2026-01-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_account_net_payment_term"),
        ("numbering_systems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="credit_note_numbering_system",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_note_numbering_account",
                to="numbering_systems.numberingsystem",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="invoice_numbering_system",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_numbering_account",
                to="numbering_systems.numberingsystem",
            ),
        ),
    ]
