# Generated by Django 5.2 on 2026-01-29 00:00

from django.db import migrations, models


def delete_rejected_invitations(apps, _):
    Invitation = apps.get_model("accounts", "Invitation")
    Invitation.objects.filter(status="rejected").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_account_credit_note_numbering_system_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_rejected_invitations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="invitation",
            name="rejected_at",
        ),
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted")], max_length=50),
        ),
    ]
