# Generated by Django 5.2 on 2026-01-30 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_invitation_rejected_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="language",
            field=models.CharField(choices=settings.LANGUAGES, default="en-us", max_length=10),
        ),
    ]
