# Generated by Django 5.2 on 2025-11-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("product_image", "Product Image"),
                    ("invoice_pdf", "Invoice Pdf"),
                    ("quote_pdf", "Quote Pdf"),
                    ("credit_note_pdf", "Credit Note Pdf"),
                    ("account_logo", "Account Logo"),
                    ("profile_avatar", "Profile Avatar"),
                    ("customer_logo", "Customer Logo"),
                ],
                max_length=50,
            ),
        ),
    ]
