# Generated by Django 5.2 on 2025-11-15 14:26

import uuid

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="model",
            field=models.CharField(
                choices=[("flat", "Flat"), ("graduated", "Graduated"), ("volume", "Volume")],
                default="flat",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="PriceTier",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("currency", models.CharField(max_length=3)),
                (
                    "unit_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("from_value", models.PositiveIntegerField()),
                (
                    "to_value",
                    models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tiers", to="prices.price"
                    ),
                ),
            ],
            options={
                "ordering": ["from_value"],
                "constraints": [
                    models.UniqueConstraint(fields=("price", "from_value"), name="unique_price_tier_from"),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("to_value__isnull", True), ("to_value__gte", models.F("from_value")), _connector="OR"
                        ),
                        name="price_tier_upper_bound",
                    ),
                ],
            },
        ),
    ]
