# Generated by Django 5.2 on 2026-01-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0003_price_model_pricetier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="is_active",
        ),
        migrations.AddField(
            model_name="price",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=20
            ),
        ),
    ]
