/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type {
  BusinessProfile,
  BusinessProfileCreate,
  BusinessProfilesListParams,
  BusinessProfileUpdate,
  PaginatedBusinessProfileList,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const businessProfilesList = (
  params?: BusinessProfilesListParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedBusinessProfileList>(
    { url: `/api/v1/business-profiles`, method: "GET", params, signal },
    options,
  );
};

export const getBusinessProfilesListQueryKey = (
  params?: BusinessProfilesListParams,
) => {
  return [`/api/v1/business-profiles`, ...(params ? [params] : [])] as const;
};

export const getBusinessProfilesListQueryOptions = <
  TData = Awaited<ReturnType<typeof businessProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BusinessProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBusinessProfilesListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof businessProfilesList>>
  > = ({ signal }) => businessProfilesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof businessProfilesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BusinessProfilesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof businessProfilesList>>
>;
export type BusinessProfilesListQueryError = ErrorType<unknown>;

export function useBusinessProfilesList<
  TData = Awaited<ReturnType<typeof businessProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | BusinessProfilesListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessProfilesList>>,
          TError,
          Awaited<ReturnType<typeof businessProfilesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBusinessProfilesList<
  TData = Awaited<ReturnType<typeof businessProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BusinessProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessProfilesList>>,
          TError,
          Awaited<ReturnType<typeof businessProfilesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBusinessProfilesList<
  TData = Awaited<ReturnType<typeof businessProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BusinessProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useBusinessProfilesList<
  TData = Awaited<ReturnType<typeof businessProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BusinessProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBusinessProfilesListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getBusinessProfilesListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof businessProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BusinessProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBusinessProfilesListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof businessProfilesList>>
  > = ({ signal }) => businessProfilesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof businessProfilesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BusinessProfilesListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof businessProfilesList>>
>;
export type BusinessProfilesListSuspenseQueryError = ErrorType<unknown>;

export function useBusinessProfilesListSuspense<
  TData = Awaited<ReturnType<typeof businessProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | BusinessProfilesListParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBusinessProfilesListSuspense<
  TData = Awaited<ReturnType<typeof businessProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BusinessProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBusinessProfilesListSuspense<
  TData = Awaited<ReturnType<typeof businessProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BusinessProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useBusinessProfilesListSuspense<
  TData = Awaited<ReturnType<typeof businessProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: BusinessProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBusinessProfilesListSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createBusinessProfile = (
  businessProfileCreate: BusinessProfileCreate,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<BusinessProfile>(
    {
      url: `/api/v1/business-profiles`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: businessProfileCreate,
      signal,
    },
    options,
  );
};

export const getCreateBusinessProfileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBusinessProfile>>,
    TError,
    { data: BusinessProfileCreate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createBusinessProfile>>,
  TError,
  { data: BusinessProfileCreate },
  TContext
> => {
  const mutationKey = ["createBusinessProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createBusinessProfile>>,
    { data: BusinessProfileCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createBusinessProfile(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateBusinessProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof createBusinessProfile>>
>;
export type CreateBusinessProfileMutationBody = BusinessProfileCreate;
export type CreateBusinessProfileMutationError = ErrorType<unknown>;

export const useCreateBusinessProfile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createBusinessProfile>>,
      TError,
      { data: BusinessProfileCreate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createBusinessProfile>>,
  TError,
  { data: BusinessProfileCreate },
  TContext
> => {
  const mutationOptions = getCreateBusinessProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const businessProfilesRetrieve = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<BusinessProfile>(
    { url: `/api/v1/business-profiles/${id}`, method: "GET", signal },
    options,
  );
};

export const getBusinessProfilesRetrieveQueryKey = (id?: string) => {
  return [`/api/v1/business-profiles/${id}`] as const;
};

export const getBusinessProfilesRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof businessProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBusinessProfilesRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof businessProfilesRetrieve>>
  > = ({ signal }) => businessProfilesRetrieve(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof businessProfilesRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BusinessProfilesRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof businessProfilesRetrieve>>
>;
export type BusinessProfilesRetrieveQueryError = ErrorType<unknown>;

export function useBusinessProfilesRetrieve<
  TData = Awaited<ReturnType<typeof businessProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessProfilesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof businessProfilesRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBusinessProfilesRetrieve<
  TData = Awaited<ReturnType<typeof businessProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof businessProfilesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof businessProfilesRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBusinessProfilesRetrieve<
  TData = Awaited<ReturnType<typeof businessProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useBusinessProfilesRetrieve<
  TData = Awaited<ReturnType<typeof businessProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBusinessProfilesRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getBusinessProfilesRetrieveSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof businessProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBusinessProfilesRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof businessProfilesRetrieve>>
  > = ({ signal }) => businessProfilesRetrieve(id, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof businessProfilesRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BusinessProfilesRetrieveSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof businessProfilesRetrieve>>
>;
export type BusinessProfilesRetrieveSuspenseQueryError = ErrorType<unknown>;

export function useBusinessProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof businessProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBusinessProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof businessProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBusinessProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof businessProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useBusinessProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof businessProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof businessProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBusinessProfilesRetrieveSuspenseQueryOptions(
    id,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateBusinessProfile = (
  id: string,
  businessProfileUpdate: BusinessProfileUpdate,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<BusinessProfile>(
    {
      url: `/api/v1/business-profiles/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: businessProfileUpdate,
    },
    options,
  );
};

export const getUpdateBusinessProfileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateBusinessProfile>>,
    TError,
    { id: string; data: BusinessProfileUpdate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateBusinessProfile>>,
  TError,
  { id: string; data: BusinessProfileUpdate },
  TContext
> => {
  const mutationKey = ["updateBusinessProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateBusinessProfile>>,
    { id: string; data: BusinessProfileUpdate }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateBusinessProfile(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateBusinessProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateBusinessProfile>>
>;
export type UpdateBusinessProfileMutationBody = BusinessProfileUpdate;
export type UpdateBusinessProfileMutationError = ErrorType<unknown>;

export const useUpdateBusinessProfile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateBusinessProfile>>,
      TError,
      { id: string; data: BusinessProfileUpdate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateBusinessProfile>>,
  TError,
  { id: string; data: BusinessProfileUpdate },
  TContext
> => {
  const mutationOptions = getUpdateBusinessProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteBusinessProfile = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<void>(
    { url: `/api/v1/business-profiles/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteBusinessProfileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteBusinessProfile>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteBusinessProfile>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteBusinessProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteBusinessProfile>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteBusinessProfile(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteBusinessProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteBusinessProfile>>
>;

export type DeleteBusinessProfileMutationError = ErrorType<unknown>;

export const useDeleteBusinessProfile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteBusinessProfile>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteBusinessProfile>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteBusinessProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
