"""
Django settings for project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from collections.abc import Callable
from pathlib import Path

import environ
import structlog
from corsheaders.defaults import default_headers
from django.utils.translation import gettext_noop
from drf_standardized_errors.openapi_serializers import ClientErrorEnum, ServerErrorEnum, ValidationErrorEnum

from common.choices import FeatureCode, LimitCode

env = environ.Env()

BASE_DIR = environ.Path(__file__) - 3
APPS_DIR = BASE_DIR.path("openinvoice")

env.read_env(Path(BASE_DIR, ".env"))

DEBUG = env.bool("DJANGO_DEBUG", default=True)

# Application definition

LOCAL_APPS = [
    "openinvoice.accounts.apps.AccountsConfig",
    "openinvoice.addresses.apps.AddressesConfig",
    "openinvoice.analytics.apps.AnalyticsConfig",
    "openinvoice.coupons.apps.CouponsConfig",
    "openinvoice.customers.apps.CustomersConfig",
    "openinvoice.files.apps.FilesConfig",
    "openinvoice.invoices.apps.InvoicesConfig",
    "openinvoice.credit_notes.apps.CreditNotesConfig",
    "openinvoice.integrations.apps.IntegrationsConfig",
    "openinvoice.integrations.stripe.apps.StripeIntegrationsConfig",
    "openinvoice.comments.apps.CommentsConfig",
    "openinvoice.numbering_systems.apps.NumberingSystemsConfig",
    "openinvoice.payments.apps.PaymentsConfig",
    "openinvoice.portal.apps.PortalConfig",
    "openinvoice.quotes.apps.QuotesConfig",
    "openinvoice.prices.apps.PricesConfig",
    "openinvoice.products.apps.ProductsConfig",
    "openinvoice.search.apps.SearchConfig",
    "openinvoice.shipping_rates.apps.ShippingRatesConfig",
    "openinvoice.stripe.apps.StripeConfig",
    "openinvoice.tax_ids.apps.TaxIdsConfig",
    "openinvoice.tax_rates.apps.TaxRatesConfig",
    "openinvoice.users.apps.UsersConfig",
]

THIRD_PARTY_APPS = [
    "allauth",
    "allauth.account",
    "allauth.headless",
    "allauth.usersessions",
    "anymail",
    "corsheaders",
    "django_countries",
    "django_filters",
    "django_structlog",
    "django_vite",
    "djmoney",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "drf_standardized_errors",
    "health_check",
    "health_check.db",
    "rest_framework",
    "rest_framework.authtoken",
    "storages",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.postgres",
    "django.contrib.humanize",
    *THIRD_PARTY_APPS,
    *LOCAL_APPS,
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Third Party
    "allauth.account.middleware.AccountMiddleware",
    "allauth.usersessions.middleware.UserSessionsMiddleware",
    "openinvoice.accounts.middlewares.AccountMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
]

ROOT_URLCONF = "config.urls"
APPEND_SLASH = False

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR.path("templates"))],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        **env.db("DJANGO_DATABASE_URL", engine="django.db.backends.postgresql"),
        "ATOMIC_REQUESTS": True,
        "CONN_MAX_AGE": env.int("DJANGO_CONN_MAX_AGE", default=60),
        "CONN_HEALTH_CHECKS": True,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

LANGUAGES = [
    ("en-us", gettext_noop("English")),
    ("en-gb", gettext_noop("British English")),
    ("en-au", gettext_noop("Australian English")),
]

COUNTRY_TO_LANUAGE = {
    "US": "en-us",
    "GB": "en-gb",
    "AU": "en-au",
}

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Localization

USE_L10N = True
LOCALE_PATHS = [str(BASE_DIR.path("locale"))]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = str(BASE_DIR.path("staticfiles"))
STATICFILES_DIRS = [str(BASE_DIR.path("static"))]

# Media files

MEDIA_URL = "/media/"
MEDIA_ROOT = str(BASE_DIR.path("mediafiles"))

FILE_UPLOAD_ACCOUNT_LOGO_POLICY = {
    "allowed_content_types": ["image/png", "image/jpeg", "image/svg+xml"],
    "max_size": 512 * 1024,
}
FILE_UPLOAD_PRODUCT_IMAGE_POLICY = {
    "allowed_content_types": ["image/png", "image/jpeg", "image/webp"],
    "max_size": 2 * 1024 * 1024,
}
FILE_UPLOAD_PROFILE_AVATAR_POLICY = {
    "allowed_content_types": ["image/png", "image/jpeg", "image/svg+xml"],
    "max_size": 512 * 1024,
}
FILE_UPLOAD_CUSTOMER_LOGO_POLICY = {
    "allowed_content_types": ["image/png", "image/jpeg", "image/svg+xml"],
    "max_size": 512 * 1024,
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    *default_headers,
    "x-email-verification-key",
]

# URLs

BASE_URL = env.str("DJANGO_API_URL", default="http://localhost:8000")
WWW_URL = "https://openinvoice.io"
BILLING_URL = BASE_URL + "/settings/billing"
PRIVACY_URL = WWW_URL + "/privacy"
TERMS_URL = WWW_URL + "/terms"
INVITATION_URL = BASE_URL + "/invitation?code={code}"

# Authentication

AUTH_USER_MODEL = "users.User"
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
SITE_ID = 1

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*"]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = True
ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS = False
ACCOUNT_MAX_EMAIL_ADDRESSES = 1
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""

USERSESSIONS_TRACK_ACTIVITY = False

HEADLESS_ONLY = True
HEADLESS_ADAPTER = "openinvoice.users.adapters.HeadlessAdapter"
HEADLESS_FRONTEND_URLS = {
    "account_reset_password": BASE_URL + "/recovery",
    "account_reset_password_from_key": BASE_URL + "/recovery/{key}",
    "account_signup": BASE_URL + "/signup",
    "socialaccount_login_error": BASE_URL + "/provider/callback",
}

# Email

DEFAULT_FROM_EMAIL = env.str("DJANGO_DEFAULT_FROM_EMAIL", default="Example <django@localhost>")
EMAIL_SUBJECT_PREFIX = ""

EMAIL_PROVIDER = env("DJANGO_EMAIL_PROVIDER", default="console")
if EMAIL_PROVIDER == "smtp":
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = env("DJANGO_EMAIL_HOST")
    EMAIL_PORT = env("DJANGO_EMAIL_PORT")
    EMAIL_USE_TLS = env("DJANGO_EMAIL_USE_TLS", default=False)
    EMAIL_TIMEOUT = env("DJANGO_EMAIL_TIMEOUT", default=5)
elif EMAIL_PROVIDER == "sendgrid":
    EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"
    ANYMAIL_SENDGRID_API_KEY = env.str("DJANGO_SENDGRID_API_KEY")
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# PDF

PDF_ENGINE = env("DJANGO_PDF_ENGINE", default="weasyprint")
if PDF_ENGINE == "gotenberg":
    PDF_GENERATOR_BACKEND = "common.pdf.backends.gotenberg.GotenbergBackend"
    GOTENBERG_URL = env.str("DJANGO_GOTENBERG_URL", default="http://localhost:3000")
    GOTENBERG_TIMEOUT = env.int("DJANGO_GOTENBERG_TIMEOUT", default=60)
else:
    PDF_GENERATOR_BACKEND = "common.pdf.backends.weasyprint.WeasyPrintBackend"

# API

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_standardized_errors.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PAGINATION_CLASS": "common.pagination.PageNumberPagination",
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": "v1",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "URL_FORMAT_OVERRIDE": None,
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}

DRF_STANDARDIZED_ERRORS: dict = {"ALLOWED_ERROR_STATUS_CODES": []}

SPECTACULAR_SETTINGS = {
    "TITLE": "Invoicence API",
    "DESCRIPTION": "Description",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "POSTPROCESSING_HOOKS": [
        "drf_standardized_errors.openapi_hooks.postprocess_schema_enums",
        "openinvoice.users.schema.postprocess_allauth_schema",
    ],
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "OPERATION_ID_METHOD_POSITION": "POST",  # TODO: change it to 'PRE'
    # Add drf standardized errors this way, because it is not used by any other path or schemas
    "APPEND_COMPONENTS": {
        "schemas": {
            "ValidationErrorEnum": {"type": "string", "enum": list(ValidationErrorEnum.values)},
            "ClientErrorEnum": {"type": "string", "enum": list(ClientErrorEnum.values)},
            "ServerErrorEnum": {"type": "string", "enum": list(ServerErrorEnum.values)},
        }
    },
    "ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE": False,  # Do not add nullEnum schemas to openapi, without it orval fails
    "ENUM_NAME_OVERRIDES": {
        "FilePurposeEnum": "openinvoice.files.choices.FilePurpose.choices",
        "MemberRoleEnum": "openinvoice.accounts.choices.MemberRole.choices",
        "InvoiceStatusEnum": "openinvoice.invoices.choices.InvoiceStatus.choices",
        "NumberingSystemResetIntervalEnum": "openinvoice.numbering_systems.choices.NumberingSystemResetInterval.choices",
        "TaxIdTypeEnum": "openinvoice.tax_ids.choices.TaxIdType.choices",
        "CurrencyEnum": "djmoney.settings.CURRENCY_CHOICES",
        "PaymentStatusEnum": "openinvoice.payments.choices.PaymentStatus.choices",
        "PaymentProviderEnum": "openinvoice.integrations.choices.PaymentProvider.choices",
        "PriceModelEnum": "openinvoice.prices.choices.PriceModel.choices",
        "CreditNoteStatusEnum": "openinvoice.credit_notes.choices.CreditNoteStatus.choices",
        "CreditNoteReasonEnum": "openinvoice.credit_notes.choices.CreditNoteReason.choices",
        "NumberingSystemAppliesToEnum": "openinvoice.numbering_systems.choices.NumberingSystemAppliesTo.choices",
        "QuoteStatusEnum": "openinvoice.quotes.choices.QuoteStatus.choices",
        # According to https://drf-spectacular.readthedocs.io/en/latest/faq.html#i-get-warnings-regarding-my-enum-or-my-enum-names-have-a-weird-suffix
        # we can't set separate names for e.g. PriceStatusEnum and TaxRateStatusEnum
        # because they use the same set of choices, so we use ProductCatalogStatusEnum
        # for all product catalog related status enums
        "ProductCatalogStatusEnum": "openinvoice.products.choices.ProductStatus.choices",
        "CommentVisibilityEnum": "openinvoice.comments.choices.CommentVisibility.choices",
    },
}

# Currencies

DEFAULT_CURRENCY = "EUR"
PROJECT_CURRENCIES = [
    "AED",
    "AFN",
    "ALL",
    "AMD",
    "ANG",
    "AOA",
    "ARS",
    "AUD",
    "AWG",
    "AZN",
    "BAM",
    "BBD",
    "BDT",
    "BGN",
    "BIF",
    "BMD",
    "BND",
    "BOB",
    "BRL",
    "BSD",
    "BWP",
    "BYN",
    "BZD",
    "CAD",
    "CDF",
    "CHF",
    "CLF",
    "CLP",
    "CNY",
    "COP",
    "CRC",
    "CVE",
    "CZK",
    "DJF",
    "DKK",
    "DOP",
    "DZD",
    "EGP",
    "ETB",
    "EUR",
    "FJD",
    "FKP",
    "GBP",
    "GEL",
    "GHS",
    "GIP",
    "GMD",
    "GNF",
    "GTQ",
    "GYD",
    "HKD",
    "HNL",
    "HRK",
    "HTG",
    "HUF",
    "IDR",
    "ILS",
    "INR",
    "ISK",
    "JMD",
    "JPY",
    "KES",
    "KGS",
    "KHR",
    "KMF",
    "KRW",
    "KYD",
    "KZT",
    "LAK",
    "LBP",
    "LKR",
    "LRD",
    "LSL",
    "MAD",
    "MDL",
    "MGA",
    "MKD",
    "MMK",
    "MNT",
    "MOP",
    "MRO",
    "MUR",
    "MVR",
    "MWK",
    "MXN",
    "MYR",
    "MZN",
    "NAD",
    "NGN",
    "NIO",
    "NOK",
    "NPR",
    "NZD",
    "PAB",
    "PEN",
    "PGK",
    "PHP",
    "PKR",
    "PLN",
    "PYG",
    "QAR",
    "RON",
    "RSD",
    "RUB",
    "RWF",
    "SAR",
    "SBD",
    "SCR",
    "SEK",
    "SGD",
    "SHP",
    "SLL",
    "SOS",
    "SRD",
    "STD",
    "SZL",
    "THB",
    "TJS",
    "TOP",
    "TRY",
    "TTD",
    "TWD",
    "TZS",
    "UAH",
    "UGX",
    "USD",
    "UYU",
    "UZS",
    "VND",
    "VUV",
    "WST",
    "XAF",
    "XCD",
    "XOF",
    "XPF",
    "YER",
    "ZAR",
    "ZMW",
]

# Logging

LOG_LEVEL = env("DJANGO_LOG_LEVEL", default="INFO")
LOG_JSON_FORMAT = env.bool("DJANGO_LOG_JSON_FORMAT", default=False)
STRUCTLOG_RENDERER_PROCESSOR = (
    structlog.dev.ConsoleRenderer() if not LOG_JSON_FORMAT else structlog.processors.JSONRenderer()
)
STRUCTLOG_PROCESSORS: list[Callable] = [
    structlog.stdlib.add_log_level,
    structlog.stdlib.add_logger_name,
    structlog.contextvars.merge_contextvars,
    structlog.processors.EventRenamer("message"),
    structlog.stdlib.ExtraAdder(),
    structlog.dev.set_exc_info,
    structlog.processors.TimeStamper(fmt="iso", utc=True),
    structlog.processors.UnicodeDecoder(),
]
if LOG_JSON_FORMAT:
    STRUCTLOG_PROCESSORS.append(structlog.processors.dict_tracebacks)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": STRUCTLOG_RENDERER_PROCESSOR,
            "foreign_pre_chain": STRUCTLOG_PROCESSORS,
        },
    },
    "handlers": {
        "default": {
            "formatter": "default",
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "": {
            "handlers": ["default"],
            "level": LOG_LEVEL,
        },
    },
}

structlog.configure_once(
    processors=[
        *STRUCTLOG_PROCESSORS,
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.make_filtering_bound_logger(LOG_LEVEL),
    cache_logger_on_first_use=True,
)

# Account

ACCOUNT_NET_PAYMENT_TERM = env("DJANGO_ACCOUNT_NET_PAYMENT_TERM", default=7)
ACCOUNT_INVOICE_NUMBERING_SYSTEM_TEMPLATE = "INV-{nnnn}"
ACCOUNT_INVOICE_NUMBERING_SYSTEM_DESCRIPTION = "Default"
ACCOUNT_CREDIT_NOTE_NUMBERING_SYSTEM_TEMPLATE = "CN-{nnnn}"
ACCOUNT_CREDIT_NOTE_NUMBERING_SYSTEM_DESCRIPTION = "Default"

# Invitations

INVITATION_EXPIRATION_DAYS = env("DJANGO_INVITATION_EXPIRATION_DAYS", default=7)

# Plans

DEFAULT_PLAN = "default"
PLANS: dict = {
    DEFAULT_PLAN: {
        "name": "",
        "features": {
            FeatureCode.AUTOMATIC_INVOICE_DELIVERY: True,
            FeatureCode.AUTOMATIC_CREDIT_NOTE_DELIVERY: True,
            FeatureCode.AUTOMATIC_QUOTE_DELIVERY: True,
            FeatureCode.CUSTOM_NUMBERING_SYSTEMS: True,
            FeatureCode.CUSTOMER_PORTAL: True,
            FeatureCode.STRIPE_INTEGRATION: True,
        },
        "limits": {
            LimitCode.MAX_ACCOUNTS: None,
            LimitCode.MAX_MEMBERS: None,
            LimitCode.MAX_CUSTOMERS: None,
            LimitCode.MAX_PRODUCTS: None,
            LimitCode.MAX_COUPONS: None,
            LimitCode.MAX_TAX_RATES: None,
            LimitCode.MAX_INVOICES_PER_MONTH: None,
            LimitCode.MAX_CREDIT_NOTES_PER_MONTH: None,
            LimitCode.MAX_QUOTES_PER_MONTH: None,
        },
        "price_id": None,
    }
}

# Invoices

MAX_DISCOUNTS = 10
MAX_TAXES = 5
MAX_REVISIONS_PER_INVOICE = 50
MAX_INVOICE_TAX_RATES = 5
MAX_INVOICE_COUPONS = 5

# Customers

CUSTOMER_TAX_RATES_LIMIT = 5

# Tax IDs

MAX_TAX_IDS = 5

# Customer portal

PORTAL_TOKEN_MAX_AGE = env.int("DJANGO_PORTAL_TOKEN_MAX_AGE", 60 * 60 * 12)  # 12 hours

# Integrations

INTEGRATIONS = {
    "stripe": "openinvoice.integrations.stripe.integration.StripeIntegration",
}
