/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type { ConfigurationResponse } from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * There are many configuration options that alter the functionality
and behavior of django-allauth, some of which can also impact the
frontend. Therefore, relevant configuration options are exposed via
this endpoint. The data returned is not user/authentication
dependent. Hence, it suffices to only fetch this data once at boot
time of your application.

 * @summary Get configuration
 */
export const getAuthConfig = (
  client: "app" | "browser",
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ConfigurationResponse>(
    { url: `/api/${client}/v1/config`, method: "GET", signal },
    options,
  );
};

export const getGetAuthConfigQueryKey = (client?: "app" | "browser") => {
  return [`/api/${client}/v1/config`] as const;
};

export const getGetAuthConfigQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthConfig>>,
  TError = ErrorType<unknown>,
>(
  client: "app" | "browser",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthConfig>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthConfigQueryKey(client);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthConfig>>> = ({
    signal,
  }) => getAuthConfig(client, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!client,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthConfig>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthConfigQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthConfig>>
>;
export type GetAuthConfigQueryError = ErrorType<unknown>;

export function useGetAuthConfig<
  TData = Awaited<ReturnType<typeof getAuthConfig>>,
  TError = ErrorType<unknown>,
>(
  client: "app" | "browser",
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthConfig>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthConfig>>,
          TError,
          Awaited<ReturnType<typeof getAuthConfig>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuthConfig<
  TData = Awaited<ReturnType<typeof getAuthConfig>>,
  TError = ErrorType<unknown>,
>(
  client: "app" | "browser",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthConfig>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthConfig>>,
          TError,
          Awaited<ReturnType<typeof getAuthConfig>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuthConfig<
  TData = Awaited<ReturnType<typeof getAuthConfig>>,
  TError = ErrorType<unknown>,
>(
  client: "app" | "browser",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthConfig>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get configuration
 */

export function useGetAuthConfig<
  TData = Awaited<ReturnType<typeof getAuthConfig>>,
  TError = ErrorType<unknown>,
>(
  client: "app" | "browser",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthConfig>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAuthConfigQueryOptions(client, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthConfigSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthConfig>>,
  TError = ErrorType<unknown>,
>(
  client: "app" | "browser",
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAuthConfig>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthConfigQueryKey(client);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthConfig>>> = ({
    signal,
  }) => getAuthConfig(client, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAuthConfig>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthConfigSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthConfig>>
>;
export type GetAuthConfigSuspenseQueryError = ErrorType<unknown>;

export function useGetAuthConfigSuspense<
  TData = Awaited<ReturnType<typeof getAuthConfig>>,
  TError = ErrorType<unknown>,
>(
  client: "app" | "browser",
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAuthConfig>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuthConfigSuspense<
  TData = Awaited<ReturnType<typeof getAuthConfig>>,
  TError = ErrorType<unknown>,
>(
  client: "app" | "browser",
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAuthConfig>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuthConfigSuspense<
  TData = Awaited<ReturnType<typeof getAuthConfig>>,
  TError = ErrorType<unknown>,
>(
  client: "app" | "browser",
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAuthConfig>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get configuration
 */

export function useGetAuthConfigSuspense<
  TData = Awaited<ReturnType<typeof getAuthConfig>>,
  TError = ErrorType<unknown>,
>(
  client: "app" | "browser",
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getAuthConfig>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAuthConfigSuspenseQueryOptions(client, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
