# Generated by Django 5.2 on 2026-01-23 18:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberingSystem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("template", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255, null=True)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[("invoice", "Invoice"), ("credit_note", "Credit Note"), ("quote", "Quote")],
                        max_length=50,
                    ),
                ),
                (
                    "reset_interval",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=20
                    ),
                ),
                ("archived_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numbering_systems",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
