# Generated by Django 5.2 on 2025-11-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numbering_systems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numberingsystem",
            name="applies_to",
            field=models.CharField(
                choices=[("invoice", "Invoice"), ("credit_note", "Credit Note"), ("quote", "Quote")], max_length=50
            ),
        ),
    ]
