# Generated by Django 5.2 on 2026-01-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("numbering_systems", "0002_alter_numberingsystem_applies_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="numberingsystem",
            name="archived_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="numberingsystem",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=20
            ),
        ),
    ]
