# Generated by Django 5.2 on 2026-02-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("prices", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="prices", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="pricetier",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tiers", to="prices.price"
            ),
        ),
        migrations.AddConstraint(
            model_name="pricetier",
            constraint=models.UniqueConstraint(fields=("price", "from_value"), name="unique_price_tier_from"),
        ),
        migrations.AddConstraint(
            model_name="pricetier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("to_value__isnull", True), ("to_value__gte", models.F("from_value")), _connector="OR"
                ),
                name="price_tier_upper_bound",
            ),
        ),
    ]
