# Generated by Django 5.2 on 2026-01-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        ("customers", "0001_initial"),
        ("files", "0001_initial"),
        ("tax_ids", "0001_initial"),
        ("tax_rates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="logo",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="customer_logo", to="files.file"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_shipping_address",
                to="addresses.address",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_ids",
            field=models.ManyToManyField(related_name="customers", to="tax_ids.taxid"),
        ),
        migrations.AddField(
            model_name="customertaxrate",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="customer_tax_rates", to="customers.customer"
            ),
        ),
        migrations.AddField(
            model_name="customertaxrate",
            name="tax_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="customer_tax_rates", to="tax_rates.taxrate"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_rates",
            field=models.ManyToManyField(
                related_name="customers", through="customers.CustomerTaxRate", to="tax_rates.taxrate"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customertaxrate",
            unique_together={("customer", "tax_rate")},
        ),
    ]
