# Generated by Django 5.2 on 2026-01-23 18:03

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("addresses", "0001_initial"),
        ("coupons", "0001_initial"),
        ("customers", "0002_initial"),
        ("files", "0001_initial"),
        ("numbering_systems", "0001_initial"),
        ("tax_ids", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceLineCoupon",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineTaxRate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceShipping",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_excluding_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_taxable_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("total_tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceShippingTaxRate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTaxAllocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("invoice", "Invoice"), ("line", "Line"), ("shipping", "Shipping")], max_length=20
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTaxRate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255, null=True)),
                ("legal_number", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_account_address",
                        to="addresses.address",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_account_logo",
                        to="files.file",
                    ),
                ),
                ("tax_ids", models.ManyToManyField(related_name="invoice_accounts", to="tax_ids.taxid")),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=255, null=True)),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("open", "Open"), ("paid", "Paid"), ("voided", "Voided")],
                        max_length=50,
                    ),
                ),
                ("issue_date", models.DateField(null=True)),
                ("sell_date", models.DateField(null=True)),
                ("due_date", models.DateField(null=True)),
                ("net_payment_term", models.IntegerField(default=7)),
                ("footer", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "subtotal_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_discount_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_excluding_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "shipping_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_credit_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_paid_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "outstanding_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("opened_at", models.DateTimeField(null=True)),
                ("paid_at", models.DateTimeField(null=True)),
                ("voided_at", models.DateTimeField(null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("custom_fields", models.JSONField(default=dict)),
                ("payment_provider", models.CharField(choices=[("stripe", "Stripe")], max_length=50, null=True)),
                ("payment_connection_id", models.UUIDField(null=True)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")], default="manual", max_length=20
                    ),
                ),
                (
                    "tax_behavior",
                    models.CharField(
                        choices=[("inclusive", "Inclusive"), ("exclusive", "Exclusive"), ("automatic", "Automatic")],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254), blank=True, default=list, size=None
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="accounts.account"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="customers.customer"
                    ),
                ),
                (
                    "numbering_system",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="numbering_systems.numberingsystem",
                    ),
                ),
                (
                    "pdf",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_pdf",
                        to="files.file",
                    ),
                ),
                (
                    "previous_revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "account_on_invoice",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="invoices.invoiceaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceCoupon",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="invoice_coupons", to="coupons.coupon"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_coupons",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="coupons",
            field=models.ManyToManyField(related_name="+", through="invoices.InvoiceCoupon", to="coupons.coupon"),
        ),
        migrations.CreateModel(
            name="InvoiceCustomer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255, null=True)),
                ("legal_number", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billing_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_customer_billing_address",
                        to="addresses.address",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_customer_logo",
                        to="files.file",
                    ),
                ),
                (
                    "shipping_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_customer_shipping_address",
                        to="addresses.address",
                    ),
                ),
                ("tax_ids", models.ManyToManyField(related_name="invoice_customers", to="tax_ids.taxid")),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer_on_invoice",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="invoices.invoicecustomer",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceDiscountAllocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source", models.CharField(choices=[("invoice", "Invoice"), ("line", "Line")], max_length=20)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="coupons.coupon"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_allocations",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceHead",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "current",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="invoices.invoice"
                    ),
                ),
                (
                    "root",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="invoices.invoice"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="head",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="revisions", to="invoices.invoicehead"
            ),
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "unit_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "unit_excluding_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "subtotal_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_discount_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_taxable_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_excluding_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("total_tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_credit_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("credit_quantity", models.BigIntegerField(default=0)),
                (
                    "outstanding_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("outstanding_quantity", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="invoices.invoice"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
