# Generated by Django 5.2 on 2026-02-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("coupons", "0001_initial"),
        ("customers", "0002_initial"),
        ("invoices", "0001_initial"),
        ("prices", "0001_initial"),
        ("shipping_rates", "0001_initial"),
        ("tax_rates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="price",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="invoice_lines", to="prices.price"
            ),
        ),
        migrations.AddField(
            model_name="invoicediscountallocation",
            name="invoice_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_allocations",
                to="invoices.invoiceline",
            ),
        ),
        migrations.AddField(
            model_name="invoicelinecoupon",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoice_line_coupons", to="coupons.coupon"
            ),
        ),
        migrations.AddField(
            model_name="invoicelinecoupon",
            name="invoice_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_line_coupons",
                to="invoices.invoiceline",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="coupons",
            field=models.ManyToManyField(related_name="+", through="invoices.InvoiceLineCoupon", to="coupons.coupon"),
        ),
        migrations.AddField(
            model_name="invoicelinetaxrate",
            name="invoice_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_line_tax_rates",
                to="invoices.invoiceline",
            ),
        ),
        migrations.AddField(
            model_name="invoicelinetaxrate",
            name="tax_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_line_tax_rates",
                to="tax_rates.taxrate",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="tax_rates",
            field=models.ManyToManyField(
                related_name="+", through="invoices.InvoiceLineTaxRate", to="tax_rates.taxrate"
            ),
        ),
        migrations.AddField(
            model_name="invoiceshipping",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_shippings",
                to="customers.shippingprofile",
            ),
        ),
        migrations.AddField(
            model_name="invoiceshipping",
            name="shipping_rate",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="shipping_rates.shippingrate"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice",
                to="invoices.invoiceshipping",
            ),
        ),
        migrations.AddField(
            model_name="invoiceshippingtaxrate",
            name="invoice_shipping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_shipping_tax_rates",
                to="invoices.invoiceshipping",
            ),
        ),
        migrations.AddField(
            model_name="invoiceshippingtaxrate",
            name="tax_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_shipping_tax_rates",
                to="tax_rates.taxrate",
            ),
        ),
        migrations.AddField(
            model_name="invoiceshipping",
            name="tax_rates",
            field=models.ManyToManyField(
                related_name="+", through="invoices.InvoiceShippingTaxRate", to="tax_rates.taxrate"
            ),
        ),
        migrations.AddField(
            model_name="invoicetaxallocation",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tax_allocations", to="invoices.invoice"
            ),
        ),
        migrations.AddField(
            model_name="invoicetaxallocation",
            name="invoice_line",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_allocations",
                to="invoices.invoiceline",
            ),
        ),
        migrations.AddField(
            model_name="invoicetaxallocation",
            name="invoice_shipping",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_allocations",
                to="invoices.invoiceshipping",
            ),
        ),
        migrations.AddField(
            model_name="invoicetaxallocation",
            name="tax_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tax_rates.taxrate"
            ),
        ),
        migrations.AddField(
            model_name="invoicetaxrate",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invoice_tax_rates", to="invoices.invoice"
            ),
        ),
        migrations.AddField(
            model_name="invoicetaxrate",
            name="tax_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoice_tax_rates", to="tax_rates.taxrate"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_rates",
            field=models.ManyToManyField(related_name="+", through="invoices.InvoiceTaxRate", to="tax_rates.taxrate"),
        ),
        migrations.AddConstraint(
            model_name="invoicecoupon",
            constraint=models.UniqueConstraint(fields=("invoice", "coupon"), name="unique_invoice_coupon_link"),
        ),
        migrations.AddConstraint(
            model_name="invoicecoupon",
            constraint=models.UniqueConstraint(fields=("invoice", "position"), name="unique_invoice_coupon_position"),
        ),
        migrations.AddIndex(
            model_name="invoicedocument",
            index=models.Index(fields=["invoice_id"], name="invoices_in_invoice_f15cb4_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicediscountallocation",
            index=models.Index(fields=["invoice_id", "source"], name="invoices_in_invoice_013152_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicediscountallocation",
            index=models.Index(fields=["invoice_line_id", "source"], name="invoices_in_invoice_40a5e7_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicediscountallocation",
            index=models.Index(fields=["invoice_id", "coupon_id"], name="invoices_in_invoice_e96a79_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicediscountallocation",
            index=models.Index(fields=["invoice_line_id", "coupon_id"], name="invoices_in_invoice_be6e09_idx"),
        ),
        migrations.AddConstraint(
            model_name="invoicediscountallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="discount_allocation_positive_amount"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelinecoupon",
            constraint=models.UniqueConstraint(
                fields=("invoice_line", "coupon"), name="unique_invoice_line_coupon_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelinecoupon",
            constraint=models.UniqueConstraint(
                fields=("invoice_line", "position"), name="unique_invoice_line_coupon_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelinetaxrate",
            constraint=models.UniqueConstraint(
                fields=("invoice_line", "tax_rate"), name="unique_invoice_line_tax_rate_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicelinetaxrate",
            constraint=models.UniqueConstraint(
                fields=("invoice_line", "position"), name="unique_invoice_line_tax_rate_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceshippingtaxrate",
            constraint=models.UniqueConstraint(
                fields=("invoice_shipping", "tax_rate"), name="unique_invoice_shipping_tax_rate_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceshippingtaxrate",
            constraint=models.UniqueConstraint(
                fields=("invoice_shipping", "position"), name="unique_invoice_shipping_tax_rate_position"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicetaxallocation",
            index=models.Index(fields=["invoice_id", "source"], name="invoices_in_invoice_83e685_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicetaxallocation",
            index=models.Index(fields=["invoice_id", "tax_rate_id"], name="invoices_in_invoice_ffd329_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicetaxallocation",
            index=models.Index(fields=["invoice_line_id", "tax_rate_id"], name="invoices_in_invoice_672c55_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicetaxallocation",
            index=models.Index(fields=["invoice_shipping_id", "tax_rate_id"], name="invoices_in_invoice_b704b5_idx"),
        ),
        migrations.AddConstraint(
            model_name="invoicetaxallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("invoice_line__isnull", False), ("invoice_shipping__isnull", True)),
                    models.Q(("invoice_line__isnull", True), ("invoice_shipping__isnull", False)),
                    _connector="OR",
                ),
                name="tax_allocation_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicetaxallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="tax_allocation_positive_amount"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicetaxrate",
            constraint=models.UniqueConstraint(fields=("invoice", "tax_rate"), name="unique_invoice_tax_rate_link"),
        ),
        migrations.AddConstraint(
            model_name="invoicetaxrate",
            constraint=models.UniqueConstraint(fields=("invoice", "position"), name="unique_invoice_tax_rate_position"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["account_id", "number"], name="account_id_number_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["head_id"], name="invoices_in_head_id_c9c85f_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["previous_revision_id"], name="invoices_in_previou_6899f3_idx"),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "draft"),
                    models.Q(("number__isnull", False), models.Q(("number", ""), _negated=True)),
                    _connector="OR",
                ),
                name="invoice_number_required_if_not_draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("previous_revision__isnull", True),
                    models.Q(("previous_revision", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="invoice_cannot_reference_itself",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("previous_revision__isnull", False)),
                fields=("previous_revision",),
                name="uniq_single_next_revision",
            ),
        ),
    ]
