# Generated by Django 5.2 on 2026-01-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_alter_invoice_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="net_payment_term",
            field=models.PositiveIntegerField(default=7),
        ),
    ]
