# Generated by Django 5.2 on 2026-01-29 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0010_remove_invoice_sell_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="description",
        ),
    ]
