# Generated by Django 5.2 on 2026-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0010_remove_invoice_sell_date"),
        ("notes", "__first__"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="description",
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.ManyToManyField(related_name="invoices", to="notes.note"),
        ),
    ]
