# Generated by Django 5.2 on 2026-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
        ("invoices", "0011_remove_invoice_description_invoice_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="comments",
            field=models.ManyToManyField(related_name="invoices", to="comments.comment"),
        ),
    ]
