# Generated by Django 5.2 on 2026-01-30 14:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_invoice_documents(apps, _):
    Invoice = apps.get_model("invoices", "Invoice")
    InvoiceDocument = apps.get_model("invoices", "InvoiceDocument")

    for invoice in Invoice.objects.all().iterator():
        account_language = getattr(invoice.account, "language", None) or settings.LANGUAGE_CODE or "en-us"
        customer_language = getattr(invoice.customer, "language", None)

        InvoiceDocument.objects.create(
            invoice_id=invoice.id,
            role="primary",
            language=customer_language or account_language,
            footer=invoice.footer,
            custom_fields=invoice.custom_fields,
            file_id=invoice.pdf_id,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_account_language"),
        ("customers", "0007_customer_language"),
        ("files", "0002_initial"),
        ("invoices", "0012_invoice_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("legal", "Legal"), ("secondary", "Secondary")], max_length=20
                    ),
                ),
                ("language", models.CharField(choices=settings.LANGUAGES, max_length=10)),
                ("footer", models.CharField(blank=True, max_length=600, null=True)),
                ("memo", models.CharField(blank=True, max_length=600, null=True)),
                ("custom_fields", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_document_pdf",
                        to="files.file",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="invoices.invoice"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["invoice_id"], name="invoices_in_invoice_f15cb4_idx"),
                    models.Index(fields=["invoice_id", "role"], name="invoices_in_invoice_35a518_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("role", "primary")),
                        fields=("invoice",),
                        name="uniq_primary_invoice_document",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "legal")), fields=("invoice",), name="uniq_legal_invoice_document"
                    ),
                ],
            },
        ),
        migrations.RunPython(create_invoice_documents, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="invoice",
            name="custom_fields",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="footer",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="pdf",
        ),
    ]
