# Generated by Django 5.2 on 2026-01-23 18:03

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("addresses", "0001_initial"),
        ("coupons", "0001_initial"),
        ("customers", "0002_initial"),
        ("files", "0001_initial"),
        ("invoices", "0001_initial"),
        ("numbering_systems", "0001_initial"),
        ("prices", "0001_initial"),
        ("tax_ids", "0001_initial"),
        ("tax_rates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255, null=True)),
                ("legal_number", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes_accounts",
                        to="accounts.account",
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_account_address",
                        to="addresses.address",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_account_logo",
                        to="files.file",
                    ),
                ),
                ("tax_ids", models.ManyToManyField(related_name="quote_accounts", to="tax_ids.taxid")),
            ],
        ),
        migrations.CreateModel(
            name="QuoteCustomer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255, null=True)),
                ("legal_number", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billing_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_customer_billing_address",
                        to="addresses.address",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes_customers",
                        to="customers.customer",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_customer_logo",
                        to="files.file",
                    ),
                ),
                (
                    "shipping_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_customer_shipping_address",
                        to="addresses.address",
                    ),
                ),
                ("tax_ids", models.ManyToManyField(related_name="quote_customers", to="tax_ids.taxid")),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=255, null=True)),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("issue_date", models.DateField(null=True)),
                ("footer", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "subtotal_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_discount_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount_excluding_tax",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("custom_fields", models.JSONField(default=dict)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatic", "Automatic")], default="manual", max_length=20
                    ),
                ),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254), blank=True, default=list, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("opened_at", models.DateTimeField(null=True)),
                ("accepted_at", models.DateTimeField(null=True)),
                ("canceled_at", models.DateTimeField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="quotes", to="accounts.account"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="quotes", to="customers.customer"
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "numbering_system",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="numbering_systems.numberingsystem",
                    ),
                ),
                (
                    "pdf",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes_pdf",
                        to="files.file",
                    ),
                ),
                (
                    "account_on_quote",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote",
                        to="quotes.quoteaccount",
                    ),
                ),
                (
                    "customer_on_quote",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote",
                        to="quotes.quotecustomer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "unit_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount_excluding_tax",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_discount_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "total_tax_amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("total_tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_lines",
                        to="prices.price",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="quotes.quote"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteDiscount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="quote_discounts", to="coupons.coupon"
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="discounts", to="quotes.quote"
                    ),
                ),
                (
                    "quote_line",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="quotes.quoteline",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteTax",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255, null=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="taxes", to="quotes.quote"
                    ),
                ),
                (
                    "quote_line",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="quotes.quoteline",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_taxes",
                        to="tax_rates.taxrate",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "canceled"]),
                    models.Q(("number__isnull", False), models.Q(("number", ""), _negated=True)),
                    _connector="OR",
                ),
                name="quote_number_required_if_not_draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotediscount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("quote_line__isnull", False)),
                fields=("quote_line", "coupon"),
                name="unique_quote_line_coupon",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotediscount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("quote_line__isnull", True)), fields=("quote", "coupon"), name="unique_quote_coupon"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotetax",
            constraint=models.UniqueConstraint(
                condition=models.Q(("quote_line__isnull", False), ("tax_rate__isnull", False)),
                fields=("quote_line", "tax_rate"),
                name="unique_quote_line_tax_rate",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotetax",
            constraint=models.UniqueConstraint(
                condition=models.Q(("quote_line__isnull", True), ("tax_rate__isnull", False)),
                fields=("quote", "tax_rate"),
                name="unique_quote_tax_rate",
            ),
        ),
    ]
