# Generated by Django 5.2 on 2026-01-23 18:03

import uuid

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        currency_field_name="currency", decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=20
                    ),
                ),
                ("archived_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="coupons", to="accounts.account"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("amount__isnull", False), ("percentage__isnull", True)),
                            models.Q(("amount__isnull", True), ("percentage__isnull", False)),
                            _connector="OR",
                        ),
                        name="check_coupon_amount_and_percentage_mutually_exclusive",
                    )
                ],
            },
        ),
    ]
