# Generated by Django 5.2 on 2026-01-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="is_active",
        ),
        migrations.AddField(
            model_name="coupon",
            name="archived_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=20
            ),
        ),
    ]
