/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type {
  PaginatedPortalInvoiceList,
  PortalCustomer,
  PortalCustomerUpdate,
  PortalInvoicesListParams,
  PortalSession,
  PortalSessionCreate,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const portalCustomerRetrieve = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PortalCustomer>(
    { url: `/api/v1/portal/customer`, method: "GET", signal },
    options,
  );
};

export const getPortalCustomerRetrieveQueryKey = () => {
  return [`/api/v1/portal/customer`] as const;
};

export const getPortalCustomerRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof portalCustomerRetrieve>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof portalCustomerRetrieve>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof axiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPortalCustomerRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof portalCustomerRetrieve>>
  > = ({ signal }) => portalCustomerRetrieve(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof portalCustomerRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PortalCustomerRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof portalCustomerRetrieve>>
>;
export type PortalCustomerRetrieveQueryError = ErrorType<unknown>;

export function usePortalCustomerRetrieve<
  TData = Awaited<ReturnType<typeof portalCustomerRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof portalCustomerRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof portalCustomerRetrieve>>,
          TError,
          Awaited<ReturnType<typeof portalCustomerRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePortalCustomerRetrieve<
  TData = Awaited<ReturnType<typeof portalCustomerRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof portalCustomerRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof portalCustomerRetrieve>>,
          TError,
          Awaited<ReturnType<typeof portalCustomerRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePortalCustomerRetrieve<
  TData = Awaited<ReturnType<typeof portalCustomerRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof portalCustomerRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function usePortalCustomerRetrieve<
  TData = Awaited<ReturnType<typeof portalCustomerRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof portalCustomerRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPortalCustomerRetrieveQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPortalCustomerRetrieveSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof portalCustomerRetrieve>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof portalCustomerRetrieve>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof axiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPortalCustomerRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof portalCustomerRetrieve>>
  > = ({ signal }) => portalCustomerRetrieve(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof portalCustomerRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PortalCustomerRetrieveSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof portalCustomerRetrieve>>
>;
export type PortalCustomerRetrieveSuspenseQueryError = ErrorType<unknown>;

export function usePortalCustomerRetrieveSuspense<
  TData = Awaited<ReturnType<typeof portalCustomerRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof portalCustomerRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePortalCustomerRetrieveSuspense<
  TData = Awaited<ReturnType<typeof portalCustomerRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof portalCustomerRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePortalCustomerRetrieveSuspense<
  TData = Awaited<ReturnType<typeof portalCustomerRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof portalCustomerRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function usePortalCustomerRetrieveSuspense<
  TData = Awaited<ReturnType<typeof portalCustomerRetrieve>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof portalCustomerRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPortalCustomerRetrieveSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updatePortalCustomer = (
  portalCustomerUpdate: PortalCustomerUpdate,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<PortalCustomer>(
    {
      url: `/api/v1/portal/customer`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: portalCustomerUpdate,
    },
    options,
  );
};

export const getUpdatePortalCustomerMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePortalCustomer>>,
    TError,
    { data: PortalCustomerUpdate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePortalCustomer>>,
  TError,
  { data: PortalCustomerUpdate },
  TContext
> => {
  const mutationKey = ["updatePortalCustomer"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePortalCustomer>>,
    { data: PortalCustomerUpdate }
  > = (props) => {
    const { data } = props ?? {};

    return updatePortalCustomer(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePortalCustomerMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePortalCustomer>>
>;
export type UpdatePortalCustomerMutationBody = PortalCustomerUpdate;
export type UpdatePortalCustomerMutationError = ErrorType<unknown>;

export const useUpdatePortalCustomer = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePortalCustomer>>,
      TError,
      { data: PortalCustomerUpdate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePortalCustomer>>,
  TError,
  { data: PortalCustomerUpdate },
  TContext
> => {
  const mutationOptions = getUpdatePortalCustomerMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const portalInvoicesList = (
  params?: PortalInvoicesListParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedPortalInvoiceList>(
    { url: `/api/v1/portal/invoices`, method: "GET", params, signal },
    options,
  );
};

export const getPortalInvoicesListQueryKey = (
  params?: PortalInvoicesListParams,
) => {
  return [`/api/v1/portal/invoices`, ...(params ? [params] : [])] as const;
};

export const getPortalInvoicesListQueryOptions = <
  TData = Awaited<ReturnType<typeof portalInvoicesList>>,
  TError = ErrorType<unknown>,
>(
  params?: PortalInvoicesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof portalInvoicesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPortalInvoicesListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof portalInvoicesList>>
  > = ({ signal }) => portalInvoicesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof portalInvoicesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PortalInvoicesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof portalInvoicesList>>
>;
export type PortalInvoicesListQueryError = ErrorType<unknown>;

export function usePortalInvoicesList<
  TData = Awaited<ReturnType<typeof portalInvoicesList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | PortalInvoicesListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof portalInvoicesList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof portalInvoicesList>>,
          TError,
          Awaited<ReturnType<typeof portalInvoicesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePortalInvoicesList<
  TData = Awaited<ReturnType<typeof portalInvoicesList>>,
  TError = ErrorType<unknown>,
>(
  params?: PortalInvoicesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof portalInvoicesList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof portalInvoicesList>>,
          TError,
          Awaited<ReturnType<typeof portalInvoicesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePortalInvoicesList<
  TData = Awaited<ReturnType<typeof portalInvoicesList>>,
  TError = ErrorType<unknown>,
>(
  params?: PortalInvoicesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof portalInvoicesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function usePortalInvoicesList<
  TData = Awaited<ReturnType<typeof portalInvoicesList>>,
  TError = ErrorType<unknown>,
>(
  params?: PortalInvoicesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof portalInvoicesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPortalInvoicesListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPortalInvoicesListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof portalInvoicesList>>,
  TError = ErrorType<unknown>,
>(
  params?: PortalInvoicesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof portalInvoicesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPortalInvoicesListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof portalInvoicesList>>
  > = ({ signal }) => portalInvoicesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof portalInvoicesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PortalInvoicesListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof portalInvoicesList>>
>;
export type PortalInvoicesListSuspenseQueryError = ErrorType<unknown>;

export function usePortalInvoicesListSuspense<
  TData = Awaited<ReturnType<typeof portalInvoicesList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | PortalInvoicesListParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof portalInvoicesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePortalInvoicesListSuspense<
  TData = Awaited<ReturnType<typeof portalInvoicesList>>,
  TError = ErrorType<unknown>,
>(
  params?: PortalInvoicesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof portalInvoicesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePortalInvoicesListSuspense<
  TData = Awaited<ReturnType<typeof portalInvoicesList>>,
  TError = ErrorType<unknown>,
>(
  params?: PortalInvoicesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof portalInvoicesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function usePortalInvoicesListSuspense<
  TData = Awaited<ReturnType<typeof portalInvoicesList>>,
  TError = ErrorType<unknown>,
>(
  params?: PortalInvoicesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof portalInvoicesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPortalInvoicesListSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createPortalSession = (
  portalSessionCreate: PortalSessionCreate,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PortalSession>(
    {
      url: `/api/v1/portal/sessions`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: portalSessionCreate,
      signal,
    },
    options,
  );
};

export const getCreatePortalSessionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPortalSession>>,
    TError,
    { data: PortalSessionCreate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPortalSession>>,
  TError,
  { data: PortalSessionCreate },
  TContext
> => {
  const mutationKey = ["createPortalSession"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPortalSession>>,
    { data: PortalSessionCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createPortalSession(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePortalSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPortalSession>>
>;
export type CreatePortalSessionMutationBody = PortalSessionCreate;
export type CreatePortalSessionMutationError = ErrorType<unknown>;

export const useCreatePortalSession = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPortalSession>>,
      TError,
      { data: PortalSessionCreate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPortalSession>>,
  TError,
  { data: PortalSessionCreate },
  TContext
> => {
  const mutationOptions = getCreatePortalSessionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
