# Generated by Django 5.2 on 2026-01-23 18:41

from django.db import migrations, models
from djmoney import settings as djmoney_settings


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(choices=djmoney_settings.CURRENCY_CHOICES, max_length=3),
        ),
        migrations.AlterField(
            model_name="invoicediscountallocation",
            name="currency",
            field=models.CharField(choices=djmoney_settings.CURRENCY_CHOICES, max_length=3),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="currency",
            field=models.CharField(choices=djmoney_settings.CURRENCY_CHOICES, max_length=3),
        ),
        migrations.AlterField(
            model_name="invoiceshipping",
            name="currency",
            field=models.CharField(choices=djmoney_settings.CURRENCY_CHOICES, max_length=3),
        ),
        migrations.AlterField(
            model_name="invoicetaxallocation",
            name="currency",
            field=models.CharField(choices=djmoney_settings.CURRENCY_CHOICES, max_length=3),
        ),
    ]
