/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type {
  PaginatedShippingProfileList,
  ShippingProfile,
  ShippingProfileCreate,
  ShippingProfilesListParams,
  ShippingProfileUpdate,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const shippingProfilesList = (
  params?: ShippingProfilesListParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PaginatedShippingProfileList>(
    { url: `/api/v1/shipping-profiles`, method: "GET", params, signal },
    options,
  );
};

export const getShippingProfilesListQueryKey = (
  params?: ShippingProfilesListParams,
) => {
  return [`/api/v1/shipping-profiles`, ...(params ? [params] : [])] as const;
};

export const getShippingProfilesListQueryOptions = <
  TData = Awaited<ReturnType<typeof shippingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: ShippingProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getShippingProfilesListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof shippingProfilesList>>
  > = ({ signal }) => shippingProfilesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shippingProfilesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ShippingProfilesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof shippingProfilesList>>
>;
export type ShippingProfilesListQueryError = ErrorType<unknown>;

export function useShippingProfilesList<
  TData = Awaited<ReturnType<typeof shippingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | ShippingProfilesListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof shippingProfilesList>>,
          TError,
          Awaited<ReturnType<typeof shippingProfilesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShippingProfilesList<
  TData = Awaited<ReturnType<typeof shippingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: ShippingProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof shippingProfilesList>>,
          TError,
          Awaited<ReturnType<typeof shippingProfilesList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShippingProfilesList<
  TData = Awaited<ReturnType<typeof shippingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: ShippingProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useShippingProfilesList<
  TData = Awaited<ReturnType<typeof shippingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: ShippingProfilesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getShippingProfilesListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getShippingProfilesListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof shippingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: ShippingProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getShippingProfilesListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof shippingProfilesList>>
  > = ({ signal }) => shippingProfilesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof shippingProfilesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ShippingProfilesListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof shippingProfilesList>>
>;
export type ShippingProfilesListSuspenseQueryError = ErrorType<unknown>;

export function useShippingProfilesListSuspense<
  TData = Awaited<ReturnType<typeof shippingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | ShippingProfilesListParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShippingProfilesListSuspense<
  TData = Awaited<ReturnType<typeof shippingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: ShippingProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShippingProfilesListSuspense<
  TData = Awaited<ReturnType<typeof shippingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: ShippingProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useShippingProfilesListSuspense<
  TData = Awaited<ReturnType<typeof shippingProfilesList>>,
  TError = ErrorType<unknown>,
>(
  params?: ShippingProfilesListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getShippingProfilesListSuspenseQueryOptions(
    params,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createShippingProfile = (
  shippingProfileCreate: ShippingProfileCreate,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ShippingProfile>(
    {
      url: `/api/v1/shipping-profiles`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: shippingProfileCreate,
      signal,
    },
    options,
  );
};

export const getCreateShippingProfileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createShippingProfile>>,
    TError,
    { data: ShippingProfileCreate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createShippingProfile>>,
  TError,
  { data: ShippingProfileCreate },
  TContext
> => {
  const mutationKey = ["createShippingProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createShippingProfile>>,
    { data: ShippingProfileCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createShippingProfile(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateShippingProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof createShippingProfile>>
>;
export type CreateShippingProfileMutationBody = ShippingProfileCreate;
export type CreateShippingProfileMutationError = ErrorType<unknown>;

export const useCreateShippingProfile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createShippingProfile>>,
      TError,
      { data: ShippingProfileCreate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createShippingProfile>>,
  TError,
  { data: ShippingProfileCreate },
  TContext
> => {
  const mutationOptions = getCreateShippingProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const shippingProfilesRetrieve = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ShippingProfile>(
    { url: `/api/v1/shipping-profiles/${id}`, method: "GET", signal },
    options,
  );
};

export const getShippingProfilesRetrieveQueryKey = (id?: string) => {
  return [`/api/v1/shipping-profiles/${id}`] as const;
};

export const getShippingProfilesRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getShippingProfilesRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof shippingProfilesRetrieve>>
  > = ({ signal }) => shippingProfilesRetrieve(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ShippingProfilesRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof shippingProfilesRetrieve>>
>;
export type ShippingProfilesRetrieveQueryError = ErrorType<unknown>;

export function useShippingProfilesRetrieve<
  TData = Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof shippingProfilesRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShippingProfilesRetrieve<
  TData = Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof shippingProfilesRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShippingProfilesRetrieve<
  TData = Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useShippingProfilesRetrieve<
  TData = Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getShippingProfilesRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getShippingProfilesRetrieveSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getShippingProfilesRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof shippingProfilesRetrieve>>
  > = ({ signal }) => shippingProfilesRetrieve(id, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ShippingProfilesRetrieveSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof shippingProfilesRetrieve>>
>;
export type ShippingProfilesRetrieveSuspenseQueryError = ErrorType<unknown>;

export function useShippingProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShippingProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShippingProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useShippingProfilesRetrieveSuspense<
  TData = Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof shippingProfilesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getShippingProfilesRetrieveSuspenseQueryOptions(
    id,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateShippingProfile = (
  id: string,
  shippingProfileUpdate: ShippingProfileUpdate,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<ShippingProfile>(
    {
      url: `/api/v1/shipping-profiles/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: shippingProfileUpdate,
    },
    options,
  );
};

export const getUpdateShippingProfileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateShippingProfile>>,
    TError,
    { id: string; data: ShippingProfileUpdate },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateShippingProfile>>,
  TError,
  { id: string; data: ShippingProfileUpdate },
  TContext
> => {
  const mutationKey = ["updateShippingProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateShippingProfile>>,
    { id: string; data: ShippingProfileUpdate }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateShippingProfile(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateShippingProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateShippingProfile>>
>;
export type UpdateShippingProfileMutationBody = ShippingProfileUpdate;
export type UpdateShippingProfileMutationError = ErrorType<unknown>;

export const useUpdateShippingProfile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateShippingProfile>>,
      TError,
      { id: string; data: ShippingProfileUpdate },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateShippingProfile>>,
  TError,
  { id: string; data: ShippingProfileUpdate },
  TContext
> => {
  const mutationOptions = getUpdateShippingProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteShippingProfile = (
  id: string,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<void>(
    { url: `/api/v1/shipping-profiles/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteShippingProfileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteShippingProfile>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteShippingProfile>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteShippingProfile"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteShippingProfile>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteShippingProfile(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteShippingProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteShippingProfile>>
>;

export type DeleteShippingProfileMutationError = ErrorType<unknown>;

export const useDeleteShippingProfile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteShippingProfile>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteShippingProfile>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteShippingProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
