/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Invoicence API
 * Description
 * OpenAPI spec version: 1.0.0
 */
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../../../lib/api/client";
import type { ErrorType } from "../../../lib/api/client";
import type { Search, SearchParams } from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const search = (
  params?: SearchParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Search>(
    { url: `/api/v1/search`, method: "GET", params, signal },
    options,
  );
};

export const getSearchQueryKey = (params?: SearchParams) => {
  return [`/api/v1/search`, ...(params ? [params] : [])] as const;
};

export const getSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({
    signal,
  }) => search(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof search>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchQueryResult = NonNullable<Awaited<ReturnType<typeof search>>>;
export type SearchQueryError = ErrorType<unknown>;

export function useSearch<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | SearchParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearch<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearch<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSearch<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSearchSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({
    signal,
  }) => search(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof search>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof search>>
>;
export type SearchSuspenseQueryError = ErrorType<unknown>;

export function useSearchSuspense<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | SearchParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchSuspense<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchSuspense<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSearchSuspense<
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorType<unknown>,
>(
  params?: SearchParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
