# Generated by Django 5.2 on 2026-01-29 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_alter_quote_numbering_system_alter_quotetax_tax_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="description",
        ),
    ]
