# Generated by Django 5.2 on 2026-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "__first__"),
        ("quotes", "0004_alter_quote_numbering_system_alter_quotetax_tax_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="description",
        ),
        migrations.AddField(
            model_name="quote",
            name="notes",
            field=models.ManyToManyField(related_name="quotes", to="notes.note"),
        ),
    ]
