# Generated by Django 5.2 on 2026-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
        ("quotes", "0005_remove_quote_description_quote_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="comments",
            field=models.ManyToManyField(related_name="quotes", to="comments.comment"),
        ),
    ]
