# Generated by Django 5.2 on 2026-02-05 17:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("product_image", "Product Image"),
                            ("invoice_pdf", "Invoice Pdf"),
                            ("quote_pdf", "Quote Pdf"),
                            ("credit_note_pdf", "Credit Note Pdf"),
                            ("account_logo", "Account Logo"),
                            ("profile_avatar", "Profile Avatar"),
                            ("customer_logo", "Customer Logo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("filename", models.CharField(max_length=1000, null=True)),
                ("content_type", models.CharField(max_length=100)),
                ("data", models.FileField(upload_to="files/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
