# Generated by Django 5.2 on 2025-11-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("credit_notes", "0002_initial"),
        ("customers", "0002_initial"),
        ("files", "0002_initial"),
        ("invoices", "0003_invoice_credit_tracking"),
        ("numbering_systems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnoteline",
            name="quantity",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("invoice",),
                name="unique_draft_credit_note_per_invoice",
            ),
        ),
    ]
