# Generated by Django 5.2 on 2026-01-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("credit_notes", "0002_initial"),
        ("files", "0001_initial"),
        ("invoices", "0001_initial"),
        ("numbering_systems", "0001_initial"),
        ("tax_rates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="credit_notes", to="invoices.invoice"
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="numbering_system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_notes",
                to="numbering_systems.numberingsystem",
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="pdf",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_notes_pdf",
                to="files.file",
            ),
        ),
        migrations.AddField(
            model_name="creditnoteline",
            name="credit_note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="credit_notes.creditnote"
            ),
        ),
        migrations.AddField(
            model_name="creditnoteline",
            name="invoice_line",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_note_lines",
                to="invoices.invoiceline",
            ),
        ),
        migrations.AddField(
            model_name="creditnotetax",
            name="credit_note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="taxes", to="credit_notes.creditnote"
            ),
        ),
        migrations.AddField(
            model_name="creditnotetax",
            name="credit_note_line",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taxes",
                to="credit_notes.creditnoteline",
            ),
        ),
        migrations.AddField(
            model_name="creditnotetax",
            name="tax_rate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_note_taxes",
                to="tax_rates.taxrate",
            ),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(fields=["account_id", "number"], name="credit_note_account_number_idx"),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(fields=["invoice_id", "created_at"], name="credit_note_inv_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "draft"),
                    models.Q(("number__isnull", False), models.Q(("number", ""), _negated=True)),
                    _connector="OR",
                ),
                name="credit_note_number_required_if_not_draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("invoice",),
                name="unique_draft_credit_note_per_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnotetax",
            constraint=models.UniqueConstraint(
                condition=models.Q(("credit_note_line__isnull", False), ("tax_rate__isnull", False)),
                fields=("credit_note_line", "tax_rate"),
                name="unique_credit_note_line_tax_rate",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditnotetax",
            constraint=models.UniqueConstraint(
                condition=models.Q(("credit_note_line__isnull", True), ("tax_rate__isnull", False)),
                fields=("credit_note", "tax_rate"),
                name="unique_credit_note_tax_rate",
            ),
        ),
    ]
