# Generated by Django 5.2 on 2026-01-23 18:41

from django.db import migrations, models
from djmoney import settings as djmoney_settings


class Migration(migrations.Migration):
    dependencies = [
        ("credit_notes", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnote",
            name="currency",
            field=models.CharField(choices=djmoney_settings.CURRENCY_CHOICES, max_length=3),
        ),
        migrations.AlterField(
            model_name="creditnoteline",
            name="currency",
            field=models.CharField(choices=djmoney_settings.CURRENCY_CHOICES, max_length=3),
        ),
        migrations.AlterField(
            model_name="creditnotetax",
            name="currency",
            field=models.CharField(choices=djmoney_settings.CURRENCY_CHOICES, max_length=3),
        ),
    ]
