# Generated by Django 5.2 on 2025-11-14 15:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_notes", "0003_alter_creditnoteline_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="delivery_method",
            field=models.CharField(
                choices=[("manual", "Manual"), ("automatic", "Automatic")], default="manual", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="recipients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), blank=True, default=list, size=None
            ),
        ),
    ]
