# Generated by Django 5.2 on 2026-01-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_notes", "0004_alter_creditnote_currency_and_more"),
        ("numbering_systems", "0001_initial"),
        ("tax_rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnote",
            name="numbering_system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_notes",
                to="numbering_systems.numberingsystem",
            ),
        ),
        migrations.AlterField(
            model_name="creditnotetax",
            name="tax_rate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_note_taxes",
                to="tax_rates.taxrate",
            ),
        ),
    ]
