# Generated by Django 5.2 on 2025-12-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_notes", "0004_creditnote_delivery_method_creditnote_recipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="payment_connection_id",
            field=models.UUIDField(null=True),
        ),
    ]
