# Generated by Django 5.2 on 2026-01-03 17:33

import uuid

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255, null=True)),
                ("currency", models.CharField(max_length=3)),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(currency_field_name="currency", decimal_places=2, max_digits=19),
                ),
                (
                    "tax_policy",
                    models.CharField(choices=[("match_goods", "Match Goods"), ("exempt", "Exempt")], max_length=16),
                ),
                ("is_active", models.BooleanField()),
                ("metadata", models.JSONField(default=dict)),
                ("archived_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_rates",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
