# Generated by Django 5.2 on 2026-01-25 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_rates", "0002_alter_shippingrate_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingrate",
            name="tax_policy",
        ),
    ]
